stages:
  - project-build
  - docker-build

variables:
  DOCKER_IMAGE_TAG: "hsaad11/test1-backend:latest"

project-build:
  stage: project-build
  image: adoptopenjdk/openjdk21:latest
  script:
    - chmod +x gradlew
    - ./gradlew build -Pwar -x test

docker-build:
  stage: docker-build
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  script:
    - docker build -t $DOCKER_IMAGE_TAG .
    - docker push $DOCKER_IMAGE_TAG
  only:
    - main
