stages:
  - build
  - docker_build

variables:
  DOCKER_IMAGE_TAG: "hsaad11/test1-backend:latest" # Remplacez par le nom de votre image Docker

project_build:
  stage: build
  image: gradle:jdk21
  script:
    - chmod +x gradlew
    - ./gradlew build -Pwar -x test
docker_build:
  stage: docker_build
  image: docker:19.03.12
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN
    - docker build -t $DOCKER_IMAGE_TAG .
    - docker push $DOCKER_IMAGE_TAG
  only:
    - main

