--
-- Création des vues de l'article de configuration CSCI_ADM
--

PROMPT Creating View 'V_TYPE_ENSEIGNANT'
CREATE OR REPLACE FORCE VIEW V_TYPE_ENSEIGNANT
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'TYPE_ENSEIGNANT'
/

PROMPT Creating View 'V_SALLE'
CREATE OR REPLACE FORCE VIEW V_SALLE
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'SALLE'
/

PROMPT Creating View 'V_PROCESSUS_STAGE'
CREATE OR REPLACE FORCE VIEW V_PROCESSUS_STAGE
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'PROCESSUS_STAGE'
/

PROMPT Creating View 'V_SEMESTRE'
CREATE OR REPLACE FORCE VIEW V_SEMESTRE
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'SEMESTRE'
/

PROMPT Creating View 'V_PAYS'
CREATE OR REPLACE FORCE VIEW V_PAYS
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'PAYS'
/

PROMPT Creating View 'V_DIPLOME'
CREATE OR REPLACE FORCE VIEW V_DIPLOME
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'DIPLOME'
/

PROMPT Creating View 'V_UNIVERSITE'
CREATE OR REPLACE FORCE VIEW V_UNIVERSITE
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'UNIVERSITE'
/

PROMPT Creating View 'V_SEXE'
CREATE OR REPLACE FORCE VIEW V_SEXE
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'SEXE'
/

PROMPT Creating View 'V_LISTE_SELECTION'
CREATE OR REPLACE FORCE VIEW V_LISTE_SELECTION
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'LISTE_SELECTION'
/

PROMPT Creating View 'V_OUI_NON'
CREATE OR REPLACE FORCE VIEW V_OUI_NON
 (CODE
 ,ABREVIATION
 ,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'OUI_NON'
/

