--
-- Création des index de l'article de configuration CSCI_ADM
--

PROMPT Creating Index 'ETU_PRO_FK_I'
CREATE INDEX ETU_PRO_FK_I ON ETUDIANT
 (ANNEE_UNIVERSITAIRE)
/

PROMPT Creating Index 'PRO_ENS_FK_I'
CREATE INDEX PRO_ENS_FK_I ON PROMOTION
 (NO_ENSEIGNANT)
/

PROMPT Creating Index 'PRO_FRM_FK_I'
CREATE INDEX PRO_FRM_FK_I ON PROMOTION
 (CODE_FORMATION)
/

PROMPT Creating Index 'EC_ENS_FK_I'
CREATE INDEX EC_ENS_FK_I ON ELEMENT_CONSTITUTIF
 (NO_ENSEIGNANT)
/

PROMPT Creating Index 'EC_UE_FK_I'
CREATE INDEX EC_UE_FK_I ON ELEMENT_CONSTITUTIF
 (CODE_FORMATION
 ,CODE_UE)
/

PROMPT Creating Index 'CAN_PRO_FK_I'
CREATE INDEX CAN_PRO_FK_I ON CANDIDAT
 (ANNEE_UNIVERSITAIRE)
/

PROMPT Creating Index 'UE_ENS_FK_I'
CREATE INDEX UE_ENS_FK_I ON UNITE_ENSEIGNEMENT
 (NO_ENSEIGNANT)
/

PROMPT Creating Index 'UE_FRM_FK_I'
CREATE INDEX UE_FRM_FK_I ON UNITE_ENSEIGNEMENT
 (CODE_FORMATION)
/


