--
-- Création des clés étrangères de l'article de configuration CSCI_ADM
--
  
PROMPT Creating Foreign Key on 'ETUDIANT'
ALTER TABLE ETUDIANT ADD (CONSTRAINT
 ETU_PRO_FK FOREIGN KEY 
  (CODE_FORMATION
  ,ANNEE_UNIVERSITAIRE) REFERENCES PROMOTION
  (CODE_FORMATION
  ,ANNEE_UNIVERSITAIRE))
/

PROMPT Creating Foreign Key on 'PROMOTION'
ALTER TABLE PROMOTION ADD (CONSTRAINT
 PRO_FRM_FK FOREIGN KEY 
  (CODE_FORMATION) REFERENCES FORMATION
  (CODE_FORMATION))
/

PROMPT Creating Foreign Key on 'PROMOTION'
ALTER TABLE PROMOTION ADD (CONSTRAINT
 PRO_ENS_FK FOREIGN KEY 
  (NO_ENSEIGNANT) REFERENCES ENSEIGNANT
  (NO_ENSEIGNANT))
/

PROMPT Creating Foreign Key on 'ELEMENT_CONSTITUTIF'
ALTER TABLE ELEMENT_CONSTITUTIF ADD (CONSTRAINT
 EC_UE_FK FOREIGN KEY 
  (CODE_FORMATION
  ,CODE_UE) REFERENCES UNITE_ENSEIGNEMENT
  (CODE_FORMATION
  ,CODE_UE))
/

PROMPT Creating Foreign Key on 'ELEMENT_CONSTITUTIF'
ALTER TABLE ELEMENT_CONSTITUTIF ADD (CONSTRAINT
 EC_ENS_FK FOREIGN KEY 
  (NO_ENSEIGNANT) REFERENCES ENSEIGNANT
  (NO_ENSEIGNANT))
/

PROMPT Creating Foreign Key on 'CANDIDAT'
ALTER TABLE CANDIDAT ADD (CONSTRAINT
 CAN_PRO_FK FOREIGN KEY 
  (CODE_FORMATION
  ,ANNEE_UNIVERSITAIRE) REFERENCES PROMOTION
  (CODE_FORMATION
  ,ANNEE_UNIVERSITAIRE))
/

PROMPT Creating Foreign Key on 'UNITE_ENSEIGNEMENT'
ALTER TABLE UNITE_ENSEIGNEMENT ADD (CONSTRAINT
 UE_ENS_FK FOREIGN KEY 
  (NO_ENSEIGNANT) REFERENCES ENSEIGNANT
  (NO_ENSEIGNANT))
/

PROMPT Creating Foreign Key on 'UNITE_ENSEIGNEMENT'
ALTER TABLE UNITE_ENSEIGNEMENT ADD (CONSTRAINT
 UE_FRM_FK FOREIGN KEY 
  (CODE_FORMATION) REFERENCES FORMATION
  (CODE_FORMATION))
/


