--
-- Création des clés primaires de l'article de configuration CSCI_ADM
--
  
PROMPT Creating Primary Key on 'ETUDIANT'
ALTER TABLE ETUDIANT
 ADD (CONSTRAINT ETU_PK PRIMARY KEY 
  (NO_ETUDIANT))
/

PROMPT Creating Primary Key on 'ENSEIGNANT'
ALTER TABLE ENSEIGNANT
 ADD (CONSTRAINT ENS_PK PRIMARY KEY 
  (NO_ENSEIGNANT))
/

PROMPT Creating Primary Key on 'PROMOTION'
ALTER TABLE PROMOTION
 ADD (CONSTRAINT PRO_PK PRIMARY KEY 
  (ANNEE_UNIVERSITAIRE
  ,CODE_FORMATION))
/

PROMPT Creating Primary Key on 'ELEMENT_CONSTITUTIF'
ALTER TABLE ELEMENT_CONSTITUTIF
 ADD (CONSTRAINT EC_PK PRIMARY KEY 
  (CODE_FORMATION
  ,CODE_UE
  ,CODE_EC))
/

PROMPT Creating Primary Key on 'CANDIDAT'
ALTER TABLE CANDIDAT
 ADD (CONSTRAINT CAN_PK PRIMARY KEY 
  (NO_CANDIDAT))
/

PROMPT Creating Primary Key on 'UNITE_ENSEIGNEMENT'
ALTER TABLE UNITE_ENSEIGNEMENT
 ADD (CONSTRAINT UE_PK PRIMARY KEY 
  (CODE_FORMATION
  ,CODE_UE))
/

PROMPT Creating Primary Key on 'FORMATION'
ALTER TABLE FORMATION
 ADD (CONSTRAINT FRM_PK PRIMARY KEY 
  (CODE_FORMATION))
/

