-- C:\Temp\05-SPI-Sprint-1\SD-Code\SD-SPI-V1.1\01-CSCI-GLOB-V1.0\01-CREATION\01-DDL\csci_auth.con
--
-- Generated for Oracle 10g on Fri Feb 27  16:17:49 2015 by Server Generator 10.1.2.11.12
  

  

PROMPT Creating Foreign Key on 'AUTHENTIFICATION'
ALTER TABLE AUTHENTIFICATION ADD (CONSTRAINT
 AUT_ETU_FK FOREIGN KEY 
  (NO_ETUDIANT) REFERENCES ETUDIANT
  (NO_ETUDIANT))
/

PROMPT Creating Foreign Key on 'AUTHENTIFICATION'
ALTER TABLE AUTHENTIFICATION ADD (CONSTRAINT
 AUT_ENS_FK FOREIGN KEY 
  (NO_ENSEIGNANT) REFERENCES ENSEIGNANT
  (NO_ENSEIGNANT))
/


