--
-- Création des tables de l'article de configuration CSCI_GLOB
--
PROMPT Creating Table 'CG_REF_CODES'
CREATE TABLE CG_REF_CODES
 (ID_CGRC NUMBER(32) NOT NULL
 ,RV_DOMAIN VARCHAR2(100) NOT NULL
 ,RV_LOW_VALUE VARCHAR2(240) NOT NULL
 ,RV_HIGH_VALUE VARCHAR2(240)
 ,RV_ABBREVIATION VARCHAR2(240)
 ,RV_MEANING VARCHAR2(240)
 )
/

PROMPT Creating Table 'AUTHENTIFICATION'
CREATE TABLE AUTHENTIFICATION
 (ID_CONNECTION NUMBER(16) NOT NULL
 ,ROLE VARCHAR2(5) NOT NULL
 ,LOGIN_CONNECTION VARCHAR2(64) NOT NULL
 ,PSEUDO_CONNECTION VARCHAR2(240)
 ,MOT_PASSE VARCHAR2(32)
 ,NO_ENSEIGNANT NUMBER(5)
 ,NO_ETUDIANT VARCHAR2(50)
 )
/

