-- C:\Temp\csci_auth.avt
--
-- Generated for Oracle 10g on Fri Mar 06  18:02:03 2015 by Server Generator 10.1.2.11.12


DELETE FROM CG_REF_CODES
WHERE RV_DOMAIN = 'ROLE'
/

INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ROLE', 'ADM', NULL, 'ADM', 'ADMINISTRATEUR')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ROLE', 'ENS', NULL, 'ENS', 'ENSEIGNANT')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ROLE', 'ETU', NULL, 'ETU', 'ETUDIANT')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ROLE', 'SEC', NULL, 'SEC', 'SECRETARIAT')
/

COMMIT
/

