--
--  Création du jeu d'essai de la table DROIT
--
Insert into DROIT (ID_EVALUATION,NO_ENSEIGNANT,CONSULTATION,DUPLICATION) values ('1','3','O','O');
Insert into DROIT (ID_EVALUATION,NO_ENSEIGNANT,CONSULTATION,DUPLICATION) values ('1','4','O','O');
Insert into DROIT (ID_EVALUATION,NO_ENSEIGNANT,CONSULTATION,DUPLICATION) values ('2','3','O','N');
Insert into DROIT (ID_EVALUATION,NO_ENSEIGNANT,CONSULTATION,DUPLICATION) values ('1','2','O','O');
