--
--  Création du jeu d'essai de la table REPONSE_QUESTION
--
Insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION,ID_QUESTION_EVALUATION,POSITIONNEMENT) values ('1','1','3');
Insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION,ID_QUESTION_EVALUATION,POSITIONNEMENT) values ('1','2','4');
Insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION,ID_QUESTION_EVALUATION,POSITIONNEMENT) values ('1','3','2');
Insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION,ID_QUESTION_EVALUATION,POSITIONNEMENT) values ('1','4','5');
Insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION,ID_QUESTION_EVALUATION,POSITIONNEMENT) values ('1','5','3');
Insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION,ID_QUESTION_EVALUATION,POSITIONNEMENT) values ('1','6','4');
Insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION,ID_QUESTION_EVALUATION,POSITIONNEMENT) values ('1','7','5');
Insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION,ID_QUESTION_EVALUATION,POSITIONNEMENT) values ('1','8','2');
Insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION,ID_QUESTION_EVALUATION,POSITIONNEMENT) values ('1','9','4');
Insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION,ID_QUESTION_EVALUATION,POSITIONNEMENT) values ('1','10','3');
Insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION,ID_QUESTION_EVALUATION,POSITIONNEMENT) values ('1','11','4');
Insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION,ID_QUESTION_EVALUATION,POSITIONNEMENT) values ('1','12','2');
Insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION,ID_QUESTION_EVALUATION,POSITIONNEMENT) values ('1','13','1');
Insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION,ID_QUESTION_EVALUATION,POSITIONNEMENT) values ('1','14','2');
Insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION,ID_QUESTION_EVALUATION,POSITIONNEMENT) values ('1','15','4');
Insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION,ID_QUESTION_EVALUATION,POSITIONNEMENT) values ('1','16','5');
Insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION,ID_QUESTION_EVALUATION,POSITIONNEMENT) values ('1','17','2');
Insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION,ID_QUESTION_EVALUATION,POSITIONNEMENT) values ('1','18','3');
Insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION,ID_QUESTION_EVALUATION,POSITIONNEMENT) values ('1','19','2');
Insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION,ID_QUESTION_EVALUATION,POSITIONNEMENT) values ('1','20','4');
Insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION,ID_QUESTION_EVALUATION,POSITIONNEMENT) values ('1','21','5');
Insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION,ID_QUESTION_EVALUATION,POSITIONNEMENT) values ('1','22','3');
Insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION,ID_QUESTION_EVALUATION,POSITIONNEMENT) values ('1','23','4');
Insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION,ID_QUESTION_EVALUATION,POSITIONNEMENT) values ('1','24','3');
Insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION,ID_QUESTION_EVALUATION,POSITIONNEMENT) values ('1','25','5');
Insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION,ID_QUESTION_EVALUATION,POSITIONNEMENT) values ('1','26','4');
Insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION,ID_QUESTION_EVALUATION,POSITIONNEMENT) values ('1','27','5');
Insert into REPONSE_QUESTION (ID_REPONSE_EVALUATION,ID_QUESTION_EVALUATION,POSITIONNEMENT) values ('1','28','4');
