--
--  Création du jeu d'essai de la table RUBRIQUE_QUESTION
--
Insert into RUBRIQUE_QUESTION (ID_RUBRIQUE,ID_QUESTION,ORDRE) values ('8','1','1');
Insert into RUBRIQUE_QUESTION (ID_RUBRIQUE,ID_QUESTION,ORDRE) values ('8','2','2');
Insert into RUBRIQUE_QUESTION (ID_RUBRIQUE,ID_QUESTION,ORDRE) values ('8','3','3');
Insert into RUBRIQUE_QUESTION (ID_RUBRIQUE,ID_QUESTION,ORDRE) values ('8','4','4');
Insert into RUBRIQUE_QUESTION (ID_RUBRIQUE,ID_QUESTION,ORDRE) values ('8','5','5');
Insert into RUBRIQUE_QUESTION (ID_RUBRIQUE,ID_QUESTION,ORDRE) values ('8','6','6');
Insert into RUBRIQUE_QUESTION (ID_RUBRIQUE,ID_QUESTION,ORDRE) values ('8','7','7');
Insert into RUBRIQUE_QUESTION (ID_RUBRIQUE,ID_QUESTION,ORDRE) values ('8','8','8');
Insert into RUBRIQUE_QUESTION (ID_RUBRIQUE,ID_QUESTION,ORDRE) values ('8','9','9');
