--
--  Création du jeu d'essai de la table RUBRIQUE
--
Insert into RUBRIQUE (ID_RUBRIQUE,TYPE,NO_ENSEIGNANT,DESIGNATION,ORDRE) values (null,'RBS',null,'COURS','1');
Insert into RUBRIQUE (ID_RUBRIQUE,TYPE,NO_ENSEIGNANT,DESIGNATION,ORDRE) values (null,'RBS',null,'COURS/TD','2');
Insert into RUBRIQUE (ID_RUBRIQUE,TYPE,NO_ENSEIGNANT,DESIGNATION,ORDRE) values (null,'RBS',null,'TD','3');
Insert into RUBRIQUE (ID_RUBRIQUE,TYPE,NO_ENSEIGNANT,DESIGNATION,ORDRE) values (null,'RBS',null,'TD/TP','4');
Insert into RUBRIQUE (ID_RUBRIQUE,TYPE,NO_ENSEIGNANT,DESIGNATION,ORDRE) values (null,'RBS',null,'TP','5');
Insert into RUBRIQUE (ID_RUBRIQUE,TYPE,NO_ENSEIGNANT,DESIGNATION,ORDRE) values (null,'RBS',null,'PROJET','6');
Insert into RUBRIQUE (ID_RUBRIQUE,TYPE,NO_ENSEIGNANT,DESIGNATION,ORDRE) values (null,'RBS',null,'BILAN','7');
Insert into RUBRIQUE (ID_RUBRIQUE,TYPE,NO_ENSEIGNANT,DESIGNATION,ORDRE) values (null,'RBS',null,'CM pré-composé','8');
