-- C:\Temp\05-SPI-Sprint-1\SD-Code\SD-SPI-AvecAPI-V1.0\04-CSCI-EVAE-1.0\01-CREATION\01-DDL\csci_evae.tab
--
-- Generated for Oracle 10g on Fri Feb 27  14:32:46 2015 by Server Generator 10.1.2.11.12
 

PROMPT Creating Table 'EVALUATION'
CREATE TABLE EVALUATION
 (ID_EVALUATION NUMBER(10,0) NOT NULL
 ,NO_ENSEIGNANT NUMBER(5) NOT NULL
 ,CODE_FORMATION VARCHAR2(8) NOT NULL
 ,ANNEE_UNIVERSITAIRE VARCHAR2(10) NOT NULL
 ,CODE_UE VARCHAR2(8) NOT NULL
 ,CODE_EC VARCHAR2(8)
 ,NO_EVALUATION NUMBER(2) NOT NULL
 ,DESIGNATION VARCHAR2(16) NOT NULL
 ,ETAT CHAR(3) DEFAULT 'ELA' NOT NULL
 ,PERIODE VARCHAR2(64)
 ,DEBUT_REPONSE DATE NOT NULL
 ,FIN_REPONSE DATE NOT NULL
 )
/

COMMENT ON COLUMN EVALUATION.NO_ENSEIGNANT IS 'Numéro unique de l''enseignant'
/

COMMENT ON COLUMN EVALUATION.CODE_FORMATION IS 'Code de la formation (Ex. : M2DOSI)'
/

COMMENT ON COLUMN EVALUATION.ANNEE_UNIVERSITAIRE IS 'année scolaire de la promotion (2004-2005)'
/

COMMENT ON COLUMN EVALUATION.CODE_UE IS 'Code de l''Unité d''Enseignement (Ex. : PSI)'
/

COMMENT ON COLUMN EVALUATION.CODE_EC IS 'Code de l''Elément Constitutif (Ex. : SD pour Serveur de Données dans l''UE PSI'
/

PROMPT Creating Table 'QUESTION_EVALUATION'
CREATE TABLE QUESTION_EVALUATION
 (ID_QUESTION_EVALUATION NUMBER(10,0) NOT NULL
 ,ID_RUBRIQUE_EVALUATION NUMBER(10,0) NOT NULL
 ,ID_QUESTION NUMBER(10,0)
 ,ID_QUALIFICATIF NUMBER(10,0)
 ,ORDRE NUMBER(2) NOT NULL
 ,INTITULE VARCHAR2(64)
 )
/

PROMPT Creating Table 'RUBRIQUE_QUESTION'
CREATE TABLE RUBRIQUE_QUESTION
 (ID_RUBRIQUE NUMBER(10,0) NOT NULL
 ,ID_QUESTION NUMBER(10,0) NOT NULL
 ,ORDRE INTEGER NOT NULL
 )
/

PROMPT Creating Table 'RUBRIQUE'
CREATE TABLE RUBRIQUE
 (ID_RUBRIQUE NUMBER(10,0) NOT NULL
 ,TYPE VARCHAR2(10) NOT NULL
 ,NO_ENSEIGNANT NUMBER(5)
 ,DESIGNATION VARCHAR2(32) NOT NULL
 ,ORDRE NUMBER
 )
/

COMMENT ON COLUMN RUBRIQUE.NO_ENSEIGNANT IS 'Numéro unique de l''enseignant'
/

PROMPT Creating Table 'RUBRIQUE_EVALUATION'
CREATE TABLE RUBRIQUE_EVALUATION
 (ID_RUBRIQUE_EVALUATION NUMBER(10,0) NOT NULL
 ,ID_EVALUATION NUMBER(10,0) NOT NULL
 ,ID_RUBRIQUE NUMBER(10,0)
 ,ORDRE NUMBER(2) NOT NULL
 ,DESIGNATION VARCHAR2(64)
 )
/

PROMPT Creating Table 'DROIT'
CREATE TABLE DROIT
 (ID_EVALUATION NUMBER(10,0) NOT NULL
 ,NO_ENSEIGNANT NUMBER(5) NOT NULL
 ,CONSULTATION CHAR(1) NOT NULL
 ,DUPLICATION CHAR(1) NOT NULL
 )
/

COMMENT ON COLUMN DROIT.NO_ENSEIGNANT IS 'Numéro unique de l''enseignant'
/

PROMPT Creating Table 'QUALIFICATIF'
CREATE TABLE QUALIFICATIF
 (ID_QUALIFICATIF NUMBER(10,0) NOT NULL
 ,MAXIMAL VARCHAR2(16) NOT NULL
 ,MINIMAL VARCHAR2(16) NOT NULL
 )
/

PROMPT Creating Table 'QUESTION'
CREATE TABLE QUESTION
 (ID_QUESTION NUMBER(10,0) NOT NULL
 ,TYPE VARCHAR2(10) NOT NULL
 ,NO_ENSEIGNANT NUMBER(5)
 ,ID_QUALIFICATIF NUMBER(10,0) NOT NULL
 ,INTITULE VARCHAR2(64) NOT NULL
 )
/

COMMENT ON COLUMN QUESTION.NO_ENSEIGNANT IS 'Numéro unique de l''enseignant'
/

PROMPT Creating Table 'REPONSE_QUESTION'
CREATE TABLE REPONSE_QUESTION
 (ID_REPONSE_EVALUATION NUMBER(10,0) NOT NULL
 ,ID_QUESTION_EVALUATION NUMBER(10,0) NOT NULL
 ,POSITIONNEMENT INTEGER
 )
/

PROMPT Creating Table 'REPONSE_EVALUATION'
CREATE TABLE REPONSE_EVALUATION
 (ID_REPONSE_EVALUATION NUMBER(10,0) NOT NULL
 ,ID_EVALUATION NUMBER(10,0) NOT NULL
 ,NO_ETUDIANT VARCHAR2(50)
 ,COMMENTAIRE VARCHAR2(512)
 ,NOM VARCHAR2(32)
 ,PRENOM VARCHAR2(32)
 )
/

COMMENT ON COLUMN REPONSE_EVALUATION.NO_ETUDIANT IS 'Numéro National de l''étudiant'
/

