-- C:\Temp\05-SPI-Sprint-1\SD-Code\SD-SPI-AvecAPI-V1.0\04-CSCI-EVAE-1.0\01-CREATION\01-DDL\csci_evae.sqs
--
-- Generated for Oracle 10g on Fri Feb 27  14:32:46 2015 by Server Generator 10.1.2.11.12
 
PROMPT Creating Sequence 'QUA_SEQ'
CREATE SEQUENCE QUA_SEQ
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

PROMPT Creating Sequence 'RUB_SEQ'
CREATE SEQUENCE RUB_SEQ
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

PROMPT Creating Sequence 'QEV_SEQ'
CREATE SEQUENCE QEV_SEQ
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

PROMPT Creating Sequence 'QUE_SEQ'
CREATE SEQUENCE QUE_SEQ
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

PROMPT Creating Sequence 'REV_SEQ'
CREATE SEQUENCE REV_SEQ
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

PROMPT Creating Sequence 'RPE_SEQ'
CREATE SEQUENCE RPE_SEQ
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

PROMPT Creating Sequence 'EVE_SEQ'
CREATE SEQUENCE EVE_SEQ
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

PROMPT Creating Sequence 'DRT_SEQ'
CREATE SEQUENCE DRT_SEQ
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

