-- C:\Temp\05-SPI-Sprint-1\SD-Code\SD-SPI-AvecAPI-V1.0\04-CSCI-EVAE-1.0\01-CREATION\01-DDL\csci_evae.con
--
-- Generated for Oracle 10g on Fri Feb 27  14:32:46 2015 by Server Generator 10.1.2.11.12
  
PROMPT Creating Primary Key on 'EVALUATION'
ALTER TABLE EVALUATION
 ADD (CONSTRAINT EVE_PK PRIMARY KEY 
  (ID_EVALUATION))
/

PROMPT Creating Primary Key on 'QUESTION_EVALUATION'
ALTER TABLE QUESTION_EVALUATION
 ADD (CONSTRAINT QEV_PK PRIMARY KEY 
  (ID_QUESTION_EVALUATION))
/

PROMPT Creating Primary Key on 'RUBRIQUE_QUESTION'
ALTER TABLE RUBRIQUE_QUESTION
 ADD (CONSTRAINT RBQ_PK PRIMARY KEY 
  (ID_RUBRIQUE
  ,ID_QUESTION))
/

PROMPT Creating Primary Key on 'RUBRIQUE'
ALTER TABLE RUBRIQUE
 ADD (CONSTRAINT RUB_PK PRIMARY KEY 
  (ID_RUBRIQUE))
/

PROMPT Creating Primary Key on 'RUBRIQUE_EVALUATION'
ALTER TABLE RUBRIQUE_EVALUATION
 ADD (CONSTRAINT REV_PK PRIMARY KEY 
  (ID_RUBRIQUE_EVALUATION))
/

PROMPT Creating Primary Key on 'DROIT'
ALTER TABLE DROIT
 ADD (CONSTRAINT DRT_PK PRIMARY KEY 
  (ID_EVALUATION
  ,NO_ENSEIGNANT))
/

PROMPT Creating Primary Key on 'QUALIFICATIF'
ALTER TABLE QUALIFICATIF
 ADD (CONSTRAINT QUA_PK PRIMARY KEY 
  (ID_QUALIFICATIF))
/

PROMPT Creating Primary Key on 'QUESTION'
ALTER TABLE QUESTION
 ADD (CONSTRAINT QUE_PK PRIMARY KEY 
  (ID_QUESTION))
/

PROMPT Creating Primary Key on 'REPONSE_QUESTION'
ALTER TABLE REPONSE_QUESTION
 ADD (CONSTRAINT RPQ_PK PRIMARY KEY 
  (ID_REPONSE_EVALUATION
  ,ID_QUESTION_EVALUATION))
/

PROMPT Creating Primary Key on 'REPONSE_EVALUATION'
ALTER TABLE REPONSE_EVALUATION
 ADD (CONSTRAINT RPE_PK PRIMARY KEY 
  (ID_REPONSE_EVALUATION))
/
