-- C:\Temp\05-SPI-Sprint-1\SD-Code\SD-SPI-AvecAPI-V1.0\04-CSCI-EVAE-1.0\01-CREATION\01-DDL\csci_evae.con
--
-- Generated for Oracle 10g on Fri Feb 27  14:32:46 2015 by Server Generator 10.1.2.11.12
  
PROMPT Creating Check Constraint on 'RUBRIQUE'
ALTER TABLE RUBRIQUE
 ADD (CONSTRAINT CK_RUB_TYPE CHECK (TYPE IN ('RBP', 'RBS')))
/
    
PROMPT Creating Check Constraint on 'QUESTION'
ALTER TABLE QUESTION
 ADD (CONSTRAINT CK_QUE_TYPE CHECK (TYPE IN ('QUP', 'QUS')))
/
 
PROMPT Creating Check Constraint on 'REPONSE_QUESTION'
ALTER TABLE REPONSE_QUESTION
 ADD (CONSTRAINT CK_RPQ_POSITIONNEMENT CHECK (POSITIONNEMENT BETWEEN 1 AND 5))
/
 
