@@02-JEU-ESSAI\formation
@@02-JEU-ESSAI\entreprise
@@02-JEU-ESSAI\enseignant
@@02-JEU-ESSAI\promotion
@@02-JEU-ESSAI\employe
@@02-JEU-ESSAI\candidat
@@02-JEU-ESSAI\etudiant
@@02-JEU-ESSAI\diplome
@@02-JEU-ESSAI\poste_entreprise
@@02-JEU-ESSAI\unite_enseignement
@@02-JEU-ESSAI\element_constitutif

@@02-JEU-ESSAI\offre_stage
@@02-JEU-ESSAI\soutenance
@@02-JEU-ESSAI\stage
@@02-JEU-ESSAI\visite_stage
@@02-JEU-ESSAI\avenant
@@02-JEU-ESSAI\contact_stage
@@02-JEU-ESSAI\structure_evaluation
@@02-JEU-ESSAI\evaluation_entreprise
@@02-JEU-ESSAI\critere_entreprise
@@02-JEU-ESSAI\notation_stage
@@02-JEU-ESSAI\code_notation
@@02-JEU-ESSAI\note_entreprise

@@02-JEU-ESSAI\QUALIFICATIF
@@02-JEU-ESSAI\QUESTION
@@02-JEU-ESSAI\RUBRIQUE
@@02-JEU-ESSAI\RUBRIQUE_QUESTION
@@02-JEU-ESSAI\EVALUATION
@@02-JEU-ESSAI\DROIT
@@02-JEU-ESSAI\RUBRIQUE_EVALUATION
@@02-JEU-ESSAI\QUESTION_EVALUATION
@@02-JEU-ESSAI\REPONSE_EVALUATION
@@02-JEU-ESSAI\REPONSE_QUESTION