-- INSERTING into CANDIDAT
Insert into "CANDIDAT" ("NO_ETUDIANT_NAT","ANNEE_PRO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_FIXE","TEL_PORT","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SELECTION_ORIGINE","SELECTION_COURANTE","REPONSE_ILI","DATE_REPONSE_ILI","REPONSE_CAN","DATE_REPONSE_CAN","NO_ORDRE") 
values ('321231','2004-2005','H','Baste','Pierre',to_date('1981-06-06','yyyy-mm-dd'),'Cesson-Sévigné','MAR','Française','02.99.32.78.12','06.23.45.98.74','Baste.P@voila.fr','6 rue Saint-Martin','35510','Cesson,-Sévigné','France','6 rue Saint-Martin','35510','Cesson-Sévigné','France','Master1 Informatique','UBO Rennes','LP','LP','O',to_date('2004-07-01','yyyy-mm-dd'),'ANN',to_date('2004-08-20','yyyy-mm-dd'),null);
Insert into "CANDIDAT" ("NO_ETUDIANT_NAT","ANNEE_PRO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_FIXE","TEL_PORT","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SELECTION_ORIGINE","SELECTION_COURANTE","REPONSE_ILI","DATE_REPONSE_ILI","REPONSE_CAN","DATE_REPONSE_CAN","NO_ORDRE") 
values ('48A765','2004-2005','H','Kerneuzet','Frédéric',to_date('1980-08-12','yyyy-mm-dd'),'Brest','CEL','Française',null,null,'frederic.kerneuzet@gicm.fr','10 rue Paul Eluard','29200','Brest','France','10 rue Paul Eluard','29200','Brest','France','Master1 Informatique','UBO Brest','LP','LP','O',to_date('2004-07-01','yyyy-mm-dd'),'ANN',to_date('2004-08-12','yyyy-mm-dd'),null);
Insert into "CANDIDAT" ("NO_ETUDIANT_NAT","ANNEE_PRO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_FIXE","TEL_PORT","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SELECTION_ORIGINE","SELECTION_COURANTE","REPONSE_ILI","DATE_REPONSE_ILI","REPONSE_CAN","DATE_REPONSE_CAN","NO_ORDRE") 
values ('142398A23C2','2004-2005','H','Mavic','Olivier',to_date('1980-03-07','yyyy-mm-dd'),'Quimper','CEL','Française','02.98.56.12.45','06.78.12.13.15','mavico@wanadoo.fr','17 rue de Kerjogu','29200','Brest','France','17 rue de Kerjogu','29200','Brest','France','Master1 Informatique','UBO Brest','LA','LP','O',to_date('2004-07-07','yyyy-mm-dd'),'CON',to_date('2004-08-13','yyyy-mm-dd'),1);
Insert into "CANDIDAT" ("NO_ETUDIANT_NAT","ANNEE_PRO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_FIXE","TEL_PORT","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SELECTION_ORIGINE","SELECTION_COURANTE","REPONSE_ILI","DATE_REPONSE_ILI","REPONSE_CAN","DATE_REPONSE_CAN","NO_ORDRE") 
values ('6589RS236F','2004-2005','F','Arnaldi','Solenn',to_date('1980-03-19','yyyy-mm-dd'),'Guingamp','CEL','Française',null,'06.88.55.78.97','solenn.arnaldi@wanadoo.fr','17 rue Laënnec','29200','Brest','France','17 rue Laënnec','29200','Brest','France','Master1 Informatique','UBO Brest','LP','LP','O',to_date('2004-07-01','yyyy-mm-dd'),'CON',to_date('2004-07-08','yyyy-mm-dd'),null);
Insert into "CANDIDAT" ("NO_ETUDIANT_NAT","ANNEE_PRO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_FIXE","TEL_PORT","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SELECTION_ORIGINE","SELECTION_COURANTE","REPONSE_ILI","DATE_REPONSE_ILI","REPONSE_CAN","DATE_REPONSE_CAN","NO_ORDRE") 
values ('361245','2004-2005','H','Troncal','Yannick',to_date('1979-06-04','yyyy-mm-dd'),'Angouleme','CEL','Française',null,'06.82.20.99.71','ytroncal@yahoo.fr','17 rue Kerabecam','29200','Brest','France','17 rue Kerabecam','29200','Brest','France','Master1 Informatique','UBO Brest','LA','LP','O',to_date('2004-07-01','yyyy-mm-dd'),'CON',to_date('2004-07-15','yyyy-mm-dd'),2);
Insert into "CANDIDAT" ("NO_ETUDIANT_NAT","ANNEE_PRO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_FIXE","TEL_PORT","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SELECTION_ORIGINE","SELECTION_COURANTE","REPONSE_ILI","DATE_REPONSE_ILI","REPONSE_CAN","DATE_REPONSE_CAN","NO_ORDRE") 
values ('20103526','2004-2005','F','Kerjean','Virginie',to_date('1981-03-28','yyyy-mm-dd'),'Brest','CEL','Française',null,'06.62.35.78.79','virginie_kerjean@yahoo.fr','199 rue du Commandant Drogou','29200','Brest','France','199 rue du Commandant Drogou','29200','Brest','France','Master1 Informatique','UBO Brest','LP','LP','O',to_date('2004-07-01','yyyy-mm-dd'),'CON',to_date('2004-07-13','yyyy-mm-dd'),null);
Insert into "CANDIDAT" ("NO_ETUDIANT_NAT","ANNEE_PRO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_FIXE","TEL_PORT","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SELECTION_ORIGINE","SELECTION_COURANTE","REPONSE_ILI","DATE_REPONSE_ILI","REPONSE_CAN","DATE_REPONSE_CAN","NO_ORDRE") 
values ('164598','2004-2005','H','Beriard','François-Xavier',to_date('1981-07-18','yyyy-mm-dd'),'Charleville-mézières','CEL','Française','02.98.01.93.40','06.12.90.35.66','fx.beriard@apinc.org','142 rue Robespierre','29200','Brest','France','142 rue Robespierre','29200','Brest','France','Master1 Informatique','UBO Brest','LP','LP','O',to_date('2004-07-01','yyyy-mm-dd'),'CON',to_date('2004-07-06','yyyy-mm-dd'),null);
Insert into "CANDIDAT" ("NO_ETUDIANT_NAT","ANNEE_PRO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_FIXE","TEL_PORT","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SELECTION_ORIGINE","SELECTION_COURANTE","REPONSE_ILI","DATE_REPONSE_ILI","REPONSE_CAN","DATE_REPONSE_CAN","NO_ORDRE") 
values ('0156523','2004-2005','H','Carriere','Guillaume',to_date('1982-06-17','yyyy-mm-dd'),'Brest','CEL','Française','02.98.92.77.34','06.76.94.89.85','gc@srbrest.com','16 rue Albert de Mun','29200','Brest','France','6 rue Albert de Mun','29200','Brest','France','Master1 Informatique','UBO Brest','LP','LP','O',to_date('2004-07-01','yyyy-mm-dd'),'CON',to_date('2004-07-06','yyyy-mm-dd'),null);
Insert into "CANDIDAT" ("NO_ETUDIANT_NAT","ANNEE_PRO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_FIXE","TEL_PORT","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SELECTION_ORIGINE","SELECTION_COURANTE","REPONSE_ILI","DATE_REPONSE_ILI","REPONSE_CAN","DATE_REPONSE_CAN","NO_ORDRE") 
values ('16894563','2004-2005','H','Frin','Ronan',to_date('1981-03-06','yyyy-mm-dd'),'Rennes','CEL','Française','02.99.64.04.78','06.63.92.05.30','frin_ronan@hotmail.com','1 rue A. Dodds','29200','Brest','France','16 rue Duguesclin','35590','L''hermitage','France','Master1 Informatique','UBO Brest','LP','LP','O',to_date('2004-07-01','yyyy-mm-dd'),'CON',to_date('2004-07-06','yyyy-mm-dd'),null);
Insert into "CANDIDAT" ("NO_ETUDIANT_NAT","ANNEE_PRO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_FIXE","TEL_PORT","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SELECTION_ORIGINE","SELECTION_COURANTE","REPONSE_ILI","DATE_REPONSE_ILI","REPONSE_CAN","DATE_REPONSE_CAN","NO_ORDRE") 
values ('18986523','2004-2005','F','Le Vaillant','Sandrine',to_date('1981-08-03','yyyy-mm-dd'),'Brest','CEL','Française','02.98.05.09.64','06.85.01.54.07','sandrine_le_vaillant@yahoo.fr','1 rue Van-Gogh','29280','Plouzané','France','1 rue Van-Gogh','29280','Plouzané','France','Master1 Informatique','UBO Brest','LP','LP','O',to_date('2004-07-01','yyyy-mm-dd'),'CON',to_date('2004-07-20','yyyy-mm-dd'),null);
Insert into "CANDIDAT" ("NO_ETUDIANT_NAT","ANNEE_PRO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_FIXE","TEL_PORT","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SELECTION_ORIGINE","SELECTION_COURANTE","REPONSE_ILI","DATE_REPONSE_ILI","REPONSE_CAN","DATE_REPONSE_CAN","NO_ORDRE") 
values ('20103546','2004-2005','F','Lemesle','Patricia',to_date('1981-06-03','yyyy-mm-dd'),'Morlaix','CEL','Française','02.98.72.00.61','06.13.66.36.01','pat.lemesle@wanadoo.fr','16 impasse de mouettes','29600','Morlaix','France','16 impasse de Mouettes','29600','Morlaix','France','Master1 Informatique','UBO Brest','LP','LP','O',to_date('2004-07-01','yyyy-mm-dd'),'CON',to_date('2004-07-07','yyyy-mm-dd'),null);
Insert into "CANDIDAT" ("NO_ETUDIANT_NAT","ANNEE_PRO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_FIXE","TEL_PORT","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SELECTION_ORIGINE","SELECTION_COURANTE","REPONSE_ILI","DATE_REPONSE_ILI","REPONSE_CAN","DATE_REPONSE_CAN","NO_ORDRE") 
values ('20168938','2004-2005','H','Lucas','Stéphane',to_date('1980-03-10','yyyy-mm-dd'),'Lannion','CEL','Française','02.96.37.74.92','06.23.39.47.52','stephane-joel.lucas@laposte.net','3 rue Lavoisier','22300','Lannion','France','3 rue Lavoisier','22300','Lannion','France','Master1 Informatique','UBO Brest','LP','LP','O',to_date('2004-07-01','yyyy-mm-dd'),'CON',to_date('2004-07-13','yyyy-mm-dd'),null);
