-- INSERTING into ETUDIANT
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('6589RS236F','2004-2005','CILI3.2','200056312','F','Arnaldi','Solenn',to_date('1980-03-19','yyyy-mm-dd'),'Guingamp','CEL','Française','06.88.55.78.97',null,'solenn.arnaldi@wanadoo.fr','17 rue Laënnec','29200','Brest','France','17 rue Laënnec','29200','Brest','France','Master1 Informatique','UBO Brest','SOA','arnaldso',null,null,null,null,'O');
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('164598','2004-2005','CILI3.1','200056313','H','Beriard','François-Xavier',to_date('1981-07-18','yyyy-mm-dd'),'Charleville-mézières','CEL','Française','06.12.90.35.66','02.98.01.93.40','fx.beriard@apinc.org','142 rue Robespierre','29200','Brest','France','142 rue Robespierre','29200','Brest','France','Master1 Informatique','UBO Brest','FXB','beriarfr',null,null,null,null,'O');
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('0156523','2004-2005','CILI3.1','200056314','H','Carriere','Guillaume',to_date('1982-06-17','yyyy-mm-dd'),'Brest','CEL','Française','06.76.94.89.85','02.98.92.77.34','gc@srbrest.com','16 rue Albert de Mun','29200','Brest','France','6 rue Albert de Mun','29200','Brest','France','Master1 Informatique','UBO Brest','GUC','carriegu',null,null,null,null,'O');
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('16894563','2004-2005','CILI3.1','200056317','H','Frin','Ronan',to_date('1981-03-06','yyyy-mm-dd'),'Rennes','CEL','Française','06.63.92.05.30','02.99.64.04.78','frin_ronan@hotmail.com','1 rue A. Dodds','29200','Brest','France','16 rue Duguesclin','35590','L''hermitage','France','Master1 Informatique','UBO Brest','ROF','frinrona',null,null,null,null,'O');
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('20103526','2004-2005','CILI3.1','200056318','F','Kerjean','Virginie',to_date('1981-03-28','yyyy-mm-dd'),'Brest','CEL','Française','06.62.35.78.79',null,'virginie_kerjean@yahoo.fr','199 rue du Commandant Drogou','29200','Brest','France','199 rue du Commandant Drogou','29200','Brest','France','Master1 Informatique','UBO Brest','VIK','kerjeavi',null,null,null,null,'O');
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('18986523','2004-2005','CILI3.1','200056320','F','Le Vaillant','Sandrine',to_date('1981-08-03','yyyy-mm-dd'),'Brest','CEL','Française','06.85.01.54.07','02.98.05.09.64','sandrine_le_vaillant@yahoo.fr','1 rue Van-Gogh','29280','Plouzané','France','1 rue Van-Gogh','29280','Plouzané','France','Master1 Informatique','UBO Brest','SLV','levailla',null,null,null,null,'O');
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('20103546','2004-2005','CILI3.2','200056321','F','Lemesle','Patricia',to_date('1981-06-03','yyyy-mm-dd'),'Morlaix','CEL','Française','06.13.66.36.01','02.98.72.00.61','pat.lemesle@wanadoo.fr','16 impasse de mouettes','29600','Morlaix','France','16 impasse de Mouettes','29600','Morlaix','France','Master1 Informatique','UBO Brest','PAL','lemespa',null,null,null,null,'O');
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('20168938','2004-2005','CILI3.2','200056322','H','Lucas','Stéphane',to_date('1980-03-10','yyyy-mm-dd'),'Lannion','CEL','Française','06.23.39.47.52','02.96.37.74.92','stephane-joel.lucas@laposte.net','3 rue Lavoisier','22300','Lannion','France','3 rue Lavoisier','22300','Lannion','France','Master1 Informatique','UBO Brest','SLU','lucasste',null,null,null,null,'O');
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('142398A23C2','2004-2005','CILI3.2','200056323','H','Mavic','Olivier',to_date('1980-03-07','yyyy-mm-dd'),'Quimper','CEL','Française','06.78.12.13.15','02.98.56.12.45','mavico@wanadoo.fr','17 rue de Kerjogu','29200','Brest','France','17 rue de Kerjogu','29200','Brest','France','Master1 Informatique','UBO Brest','OLM','mavicoli',null,null,null,null,'O');
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('361245','2004-2005','CILI3.2','200056312','H','Troncal','Yannick',to_date('1979-06-04','yyyy-mm-dd'),'Angouleme','CEL','Française','06.82.20.99.71',null,'ytroncal@yahoo.fr','17 rue Kerabecam','29200','Brest','France','17 rue Kerabecam','29200','Brest','France','Master1 Informatique','UBO Brest','YAT','troncaya',null,null,null,null,'O');
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('1496024035g','2005-2006','CILI4.1','20203300','F','Raoul','Aurélie',to_date('1981-04-08','yyyy-mm-dd'),'Guingamp','CEL','Française','06.64.91.49.04',null,'aurao08@yahoo.fr','App. 311, 6 rue des archives','29200','Brest','France','2 Kerbré','22540','Pédernec','France','Master1 Informatique','UBO Brest','AUR','raoulaur',null,null,null,null,'O');
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('1499067588s','2005-2006','CILI4.1','20203186','H','Gaonach','Julien',to_date('1981-09-23','yyyy-mm-dd'),'Landernau','CEL','Française','06.76.99.41.48',null,'julien_gaonach@yahoo.fr','19 kerbrad','29470','Plougastel-Daoulas','France','19 kerbrad','29470','Plougastel-Daoulas','France','Master1 Informatique','UBO Brest','JUG','gaonacju',null,null,null,null,'O');
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('1492092540t','2005-2006','CILI4.1','20105004','H','Humbert','Erwan',to_date('1982-02-01','yyyy-mm-dd'),'Paris 11ème','CEL','Française','06.81.37.85.18',null,'erwan.humbert@gmail.com','23 rue Saint Marc','29200','Brest','France','10 rue Henri Dunant','29000','Quimper','France','Master1 Informatique','UBO Brest','ERH','humberer',null,null,null,null,'O');
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('07is8800515','2005-2006','CILI4.1','20304099','H','Barzic','Ronan',to_date('1982-08-28','yyyy-mm-dd'),'Pont-L''Abbe','CEL','Française','06.71.18.27.02',null,'rbarzic@hotmail.com','35 rue Turenne','29200','Brest','France','5 rue de Coat bihan','29900','Concarneau','France','Master1 Informatique','UBO Brest','ROB','barzicro',null,null,null,null,'O');
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('1493010305n','2005-2006','CILI4.1','20304099','H','Quéffélec','Régis',to_date('1982-01-28','yyyy-mm-dd'),'Quimper','CEL','Française','06.71.85.85.19',null,'queffelec.regis@wanadoo.fr','31 rue Mirabeau','29200','Brest','France','route de kervinic','29590','Loperec','France','Master1 Informatique','UBO Brest','REQ','queffere',null,null,null,null,'O');
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('1492057895k','2005-2006','CILI4.2','20303736','H','Le Nir','David',to_date('1981-11-21','yyyy-mm-dd'),'Pont L''Abbé','CEL','Française','06.61.14.92.01',null,'david.lenir@gmail.com','Kerbenfous','29120','Tréméoc','France','Kerbenfous','29120','Tréméoc','France','Master1 Informatique','UBO Brest','DAL','le_nirda',null,null,null,null,'O');
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('06816q06pf3','2005-2006','CILI4.2','9308691R','H','Decourchelle','Antonin',to_date('1974-04-13','yyyy-mm-dd'),'Blois (41)','CEL','Française','06.63.90.96.36',null,'antonin.decourchelle@gmail.com','Keriars','29280','Plouzané','France','Keriars','29280','Plouzané','France','Master1 Informatique','UBO Brest','AND','decouran',null,null,null,null,'O');
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('1499110659h','2005-2006','CILI4.2','20504399','H','Lorand','Mickaël',to_date('1982-03-26','yyyy-mm-dd'),'Ploërmel (56)','CEL','Française','06.70.83.75.01',null,'dralak@gmail.com','2 et 4 rue des Archives','29200','Brest','France','16 rue de l''Ouest','35600','Redon','France','Master1 Informatique','Université de Rennes 1','MIL','lorandmi',null,null,null,null,'O');
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('1893029650z','2005-2006','CILI4.2','20203203','H','Naretto','Pierre-Emmanuel',to_date('1980-04-26','yyyy-mm-dd'),'Chateauroux (36)','CEL','Française','06.63.79.97.01',null,'pierre_naretto@yahoo.fr','48 Pen Ar Menez','29200','Brest','France','48 Pen Ar Menez','29200','Brest','France','Master1 Informatique','UBO Brest','PIN','narettpi',null,null,null,null,'O');
Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI","UBO_EMAIL","GRPE_ANGLAIS","ABANDON_MOTIF","ABANDON_DATE","EST_DIPLOME") 
values ('1493003704n','2005-2006','CILI4.2','20203100','H','Allain','Tangi',to_date('1982-10-03','yyyy-mm-dd'),'Douarnenez','CEL','Française','06.13.92.55.31',null,'allain_tangi@yahoo.fr','App. 222 - 6 rue des Archives','29200','Brest','France','11 rue des moineaux','29100','Douarnenez','France','Master1 Informatique','UBO Brest','ALT','allainta',null,null,null,null,'O');
