-- INSERTING into OFFRE_STAGE

INSERT INTO OFFRE_STAGE (NO_OFFRE, NO_ENTREPRISE, NO_OFFRE_ENTREPRISE, ANNEE_PRO, INTITULE, SUJET, DATE_CREATION, DUREE, ETAT_OFFRE, LIEU, NIVEAU_REQUIS, PERIODE, NOM_RESPONSABLE, PRENOM_RESPONSABLE, TEL_RESPONSABLE, MAIL_RESPONSABLE, REMUNERATION) 
VALUES ('4','8', 'WEST/NAN/MCSE/STG', '2005-2006', 'STAGE MAQUETTAGE DE COMPOSANTS D''UN SIMULATEUR D''ENTRAINEMENT NAVAL 2006', 'STAGE MAQUETTAGE DE COMPOSANTS D''UN SIMULATEUR D''ENTRAINEMENT NAVAL 2006', to_date('2006-09-03','yyyy-mm-dd'), '6 mois', 'OUV', 'Brest', 'BAC+5', 'Février à Septembre (selon école)', 'DRH', 'Service Recrutement', '', '', '0');
UPDATE OFFRE_STAGE SET DESCRIPTION='Atos Origin est l''un des principaux acteurs dans les domaines des services informatiques. Sa mission est de traduire la vision stratégique de ses clients en résultats par une meilleure utilisation de solutions de conseil, d''intégration et d''infogérance. Implanté dans 40 pays à travers le monde, Atos Origin réalise un chiffre d''affaires annuel de plus de 5 milliards d''euros avec un effectif supérieur à 46000 personnes. Atos Origin est le partenaire mondial des Jeux Olympiques. Au cœur du groupe Atos Origin, l''activité Systems Integration a pour vocation d''imaginer, de développer et de maintenir les systèmes d''information des entreprises. Le stage s''inscrit dans le cadre du projet PFE Sycops (Système de Combat Commun Barracuda et SNLE SG4) réalisé par Atos Origin pour le compte de la DCN de Brest (secteur défense). Ce projet recouvre l''étude, la réalisation et l''assistance à la mise en phase opérationnelle d''un simulateur d''entraînement et d''instruction pour le personnel navigant à bord des sous-marins nouvelle génération. Les entraînements propres aux élèves, s''effectuent de manière individuelle ou par équipe sur la base de scénarios conduits par un ou plusieurs instructeurs. Les principaux domaines didacticiels sont la détection sous-marine passive, la classification, le management de combat, le lancement des armes ainsi que le débriefing. Intégré au sein d''une équipe, vous serez chargé, à partir des résultats d''études de modélisation (Together sous Eclipse), de maquetter les applications ou les composants associés de type interface utilisateurs et techniques.Les outils qui seront mis en œuvre dans le cadre du stage reposent principalement sur l''atelier de développement Java et notamment Eclipse.L''outil de gestion de configuration sera CVS sous Eclipse.Le domaine fonctionnel concerne principalement la simulation temps réel.> Objectif pédagogique :A l''issue de cette mission, vous aurez développé une bonne approche sur le cycle de vie d''un projet réalisé au forfait et en équipe intégrée (Atos Origin et Thalès Services).La mission se déroulera à Brest. Le projet est réalisé en collaboration avec Thalès services Brest.' WHERE NO_OFFRE='4';


Insert into "OFFRE_STAGE" ("NO_OFFRE","NO_ENTREPRISE","NO_OFFRE_ENTREPRISE","ANNEE_PRO","INTITULE","SUJET","DATE_CREATION","DESCRIPTION","DUREE","ETAT_OFFRE","LIEU","NIVEAU_REQUIS","PERIODE","NOM_RESPONSABLE","PRENOM_RESPONSABLE","TEL_RESPONSABLE","MAIL_RESPONSABLE","REMUNERATION") 
values (5,1,'LEJ/SPF/REN','2005-2006','CHEF DE PROJET DE DEPLOIEMENT INFRASTRUCTURES TELECOM','CHEF DE PROJET DE DEPLOIEMENT INFRASTRUCTURES TELECOM',to_date('2006-10-03','yyyy-mm-dd'),'Dans le cadre de ses activités auprès des Opérateurs de Télécommunication, Thalès Services souhaite renforcer ses équipes de déploiement dinfrastructures. Vous assurerez la coordination du déploiement dinfrastructures télécom (Fibre Optique, FH, WIFI, WIMAX, &) sur le territoire national. Chef de projet expérimenté, vous justifiez d''une expérience significative dans le déploiement et la coordination de prestataires de services. Vous avez une bonne connaissance des infrastructures dOpérateur Télécom (TRANS, OPTIQUE, IP&). Rigueur, diplomatie et capacités relationnelles sont des qualités qui feront la différence. Merci denvoyer votre candidature par e-mail à ladresse suivante : agence.rennes@thalesgroup.com.','6 mois','OUV','Brest','BAC+5','Avril à Septembre','THALES SERVICES','DRH',null,null,'0');


Insert into "OFFRE_STAGE" ("NO_OFFRE","NO_ENTREPRISE","NO_OFFRE_ENTREPRISE","ANNEE_PRO","INTITULE","SUJET","DATE_CREATION","DESCRIPTION","DUREE","ETAT_OFFRE","LIEU","NIVEAU_REQUIS","PERIODE","NOM_RESPONSABLE","PRENOM_RESPONSABLE","TEL_RESPONSABLE","MAIL_RESPONSABLE","REMUNERATION") 
values (1,3,'Sujet 1','2005-2006','Système d''information','Évolution d''un Intranet de gestion de projet',to_date('2006-10-03','yyyy-mm-dd'),'Dans le cadre de son activité Lannionaise, Teamlog mène des projets de type TMA (Tierce Maintenance Applicative).Ce type de projet implique des engagements forts de la part de Teamlog sur la capacité de ses équipes à traiter les demandes des clients de manière très réactive. Pour faciliter la traçabilité des demandes et des actions, Teamlog Lannion a réalisé un extranet à destination de ses collaborateurs et de ses clients pour répondre aux besoins de suivi.     Largement utilisé depuis 2 ans par l''agence de Lannion, puis par les autres agences de Teamlog Ouest, une nouvelle version est prévue pour la fin de l''été 2006.Les évolutions apportées porteront sur le calcule puis l''affichage de statistiques, l''émission de rapports, l''ajout de fonction de suivi de projet, l''ajout de fonction de suivi de versions des applications gérées par Teamlog.     L''application est basée sur des environnements Open Source. La réalisation des évolutions nécessitera probablement la mise en Suvre de librairies type JGraph et/ou JChart. Le stage sera mené en mode projet : spécifications, conception, réalisation et tests au sein des équipes de l''agence de Lannion.        Technologies mises en Suvre : Java/J2EE, Tomcat, Struts, Eclipse, MySQL, XSL-FO','6 mois','OUV','Lannion','BAC+5','Avril à Septembre','Raveneau','Olivier','02.96.48.55.09','olivier.raveneau@teamlog.com','600');


Insert into "OFFRE_STAGE" ("NO_OFFRE","NO_ENTREPRISE","NO_OFFRE_ENTREPRISE","ANNEE_PRO","INTITULE","SUJET","DATE_CREATION","DESCRIPTION","DUREE","ETAT_OFFRE","LIEU","NIVEAU_REQUIS","PERIODE","NOM_RESPONSABLE","PRENOM_RESPONSABLE","TEL_RESPONSABLE","MAIL_RESPONSABLE","REMUNERATION") 
values (2,3,'Sujet 2','2005-2006','VoIP','Réalisation de briques réutilisables pour des services VoIP',to_date('2006-10-03','yyyy-mm-dd'),'Dans le cadre de son activité Lannionaise, Teamlog réalise pour ses clients des services basés sur des solutions voix sur IP destiné à des équipements types LiveBox. Ces services nécessitent la mise en Suvre de composants logiciels pour l''émission de vidéo, d''images, de texte et de son sur protocole RTP avec une signalisation SIP. Teamlog souhaite faire réaliser une bibliothèque de composants Java réutilisables par ces différents services. Réalisé en mode projet (spécifications, conception ...) au sein des équipes de Teamlog Lannion, le stage sera organisé avec phase de montée en compétence, prototypage et développement et avec le soutien des experts locaux. Technologies mises en Suvre : Java/J2EE, JMF (Java Media Framework), SIP-Servlet, Eclipse','6 mois','OUV','Lannion','BAC+5','Avril à Septembre','Raveneau','Olivier','02.96.48.55.09','olivier.raveneau@teamlog.com','600');


INSERT INTO "OFFRE_STAGE" (NO_OFFRE, NO_ENTREPRISE, NO_OFFRE_ENTREPRISE, ANNEE_PRO, INTITULE, SUJET, DATE_CREATION, DUREE, ETAT_OFFRE, LIEU, NIVEAU_REQUIS, PERIODE, NOM_RESPONSABLE, PRENOM_RESPONSABLE, TEL_RESPONSABLE, MAIL_RESPONSABLE, REMUNERATION) 
VALUES ('3', '8', 'WEST/NAN/MCSE/STG', '2004-2005', 'STAGE MAQUETTAGE DE COMPOSANTS D''UN SIMULATEUR D''ENTRAINEMENT NAVAL', 'STAGE MAQUETTAGE DE COMPOSANTS D''UN SIMULATEUR D''ENTRAINEMENT NAVAL', to_date('2006-10-03','yyyy-mm-dd'), '6 mois', 'OUV', 'Brest', 'BAC+5', 'Février à Septembre (selon école)', 'DRH', 'Service Recrutement', '', '', '0');

UPDATE OFFRE_STAGE SET DESCRIPTION='Atos Origin est l''un des principaux acteurs dans les domaines des services informatiques. Sa mission est de traduire la vision stratégique de ses clients en résultats par une meilleure utilisation de solutions de conseil, d''intégration et d''infogérance. Implanté dans 40 pays à travers le monde, Atos Origin réalise un chiffre d''affaires annuel de plus de 5 milliards d''euros avec un effectif supérieur à 46000 personnes. Atos Origin est le partenaire mondial des Jeux Olympiques. Au cœur du groupe Atos Origin, l''activité Systems Integration a pour vocation d''imaginer, de développer et de maintenir les systèmes d''information des entreprises. Le stage s''inscrit dans le cadre du projet PFE Sycops (Système de Combat Commun Barracuda et SNLE SG4) réalisé par Atos Origin pour le compte de la DCN de Brest (secteur défense). Ce projet recouvre l''étude, la réalisation et l''assistance à la mise en phase opérationnelle d''un simulateur d''entraînement et d''instruction pour le personnel navigant à bord des sous-marins nouvelle génération. Les entraînements propres aux élèves, s''effectuent de manière individuelle ou par équipe sur la base de scénarios conduits par un ou plusieurs instructeurs. Les principaux domaines didacticiels sont la détection sous-marine passive, la classification, le management de combat, le lancement des armes ainsi que le débriefing. Intégré au sein d''une équipe, vous serez chargé, à partir des résultats d''études de modélisation (Together sous Eclipse), de maquetter les applications ou les composants associés de type interface utilisateurs et techniques.Les outils qui seront mis en œuvre dans le cadre du stage reposent principalement sur l''atelier de développement Java et notamment Eclipse.L''outil de gestion de configuration sera CVS sous Eclipse.Le domaine fonctionnel concerne principalement la simulation temps réel.> Objectif pédagogique :A l''issue de cette mission, vous aurez développé une bonne approche sur le cycle de vie d''un projet réalisé au forfait et en équipe intégrée (Atos Origin et Thalès Services).La mission se déroulera à Brest. Le projet est réalisé en collaboration avec Thalès services Brest.' WHERE NO_OFFRE='3';
