Insert into STAGE (ANNEE_PRO,NO_ETUDIANT_NAT,NO_ENTREPRISE,NO_OFFRE,NO_CONTACT_ILI,INTITULE,SUJET,DATE_DEB,DATE_FIN,LIEU,ETAT_STAGE,DESCRIPTION,ETAT_CONVENTION,DATE_SIGNATURE_CONV,NO_ENSEIGNANT,COMMENTAIRE_TUTEUR,DATE_RECEPTION_RAPPORT,NOTE_ENTREPRISE,NOTE_RAPPORT,NO_SESSION,NOTE_SOUTENANCE) 
values ('2004-2005','6589RS236F',0,null,0,'Non Défini','Non Défini',to_timestamp('10/10/12 16:14:53,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('10/10/12 16:14:53,000000000','DD/MM/RR HH24:MI:SS,FF'),'Non Défini','ELA',null,'ELA',null,null,null,null,null,null,null,null);

Insert into STAGE (ANNEE_PRO,NO_ETUDIANT_NAT,NO_ENTREPRISE,NO_OFFRE,NO_CONTACT_ILI,INTITULE,SUJET,DATE_DEB,DATE_FIN,LIEU,ETAT_STAGE,DESCRIPTION,ETAT_CONVENTION,DATE_SIGNATURE_CONV,NO_ENSEIGNANT,COMMENTAIRE_TUTEUR,DATE_RECEPTION_RAPPORT,NOTE_ENTREPRISE,NOTE_RAPPORT,NO_SESSION,NOTE_SOUTENANCE) 
values ('2004-2005','164598',0,null,0,'Non Défini','Non Défini',to_timestamp('10/10/12 16:14:53,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('10/10/12 16:14:53,000000000','DD/MM/RR HH24:MI:SS,FF'),'Non Défini','ELA',null,'ELA',null,null,null,null,null,null,null,null);

Insert into STAGE (ANNEE_PRO,NO_ETUDIANT_NAT,NO_ENTREPRISE,NO_OFFRE,NO_CONTACT_ILI,INTITULE,SUJET,DATE_DEB,DATE_FIN,LIEU,ETAT_STAGE,DESCRIPTION,ETAT_CONVENTION,DATE_SIGNATURE_CONV,NO_ENSEIGNANT,COMMENTAIRE_TUTEUR,DATE_RECEPTION_RAPPORT,NOTE_ENTREPRISE,NOTE_RAPPORT,NO_SESSION,NOTE_SOUTENANCE) 
values ('2004-2005','0156523',0,null,0,'Non Défini','Non Défini',to_timestamp('10/10/12 16:14:53,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('10/10/12 16:14:53,000000000','DD/MM/RR HH24:MI:SS,FF'),'Non Défini','ELA',null,'ELA',null,null,null,null,null,null,null,null);

Insert into STAGE (ANNEE_PRO,NO_ETUDIANT_NAT,NO_ENTREPRISE,NO_OFFRE,NO_CONTACT_ILI,INTITULE,SUJET,DATE_DEB,DATE_FIN,LIEU,ETAT_STAGE,DESCRIPTION,ETAT_CONVENTION,DATE_SIGNATURE_CONV,NO_ENSEIGNANT,COMMENTAIRE_TUTEUR,DATE_RECEPTION_RAPPORT,NOTE_ENTREPRISE,NOTE_RAPPORT,NO_SESSION,NOTE_SOUTENANCE) 
values ('2004-2005','16894563',8,null,9,'Système d''information','Créer un système d''information pour gérer l''échange de document au sein de la société',to_timestamp('04/04/05 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('30/09/05 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),'Brest','ELA',null,'ELA',null,null,null,null,null,null,null,null);

Insert into STAGE (ANNEE_PRO,NO_ETUDIANT_NAT,NO_ENTREPRISE,NO_OFFRE,NO_CONTACT_ILI,INTITULE,SUJET,DATE_DEB,DATE_FIN,LIEU,ETAT_STAGE,DESCRIPTION,ETAT_CONVENTION,DATE_SIGNATURE_CONV,NO_ENSEIGNANT,COMMENTAIRE_TUTEUR,DATE_RECEPTION_RAPPORT,NOTE_ENTREPRISE,NOTE_RAPPORT,NO_SESSION,NOTE_SOUTENANCE) 
values ('2004-2005','20103526',0,null,0,'Non Défini','Non Défini',to_timestamp('10/10/12 16:14:53,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('10/10/12 16:14:53,000000000','DD/MM/RR HH24:MI:SS,FF'),'Non Défini','ELA',null,'ELA',null,null,null,null,null,null,null,null);

Insert into STAGE (ANNEE_PRO,NO_ETUDIANT_NAT,NO_ENTREPRISE,NO_OFFRE,NO_CONTACT_ILI,INTITULE,SUJET,DATE_DEB,DATE_FIN,LIEU,ETAT_STAGE,DESCRIPTION,ETAT_CONVENTION,DATE_SIGNATURE_CONV,NO_ENSEIGNANT,COMMENTAIRE_TUTEUR,DATE_RECEPTION_RAPPORT,NOTE_ENTREPRISE,NOTE_RAPPORT,NO_SESSION,NOTE_SOUTENANCE) 
values ('2004-2005','18986523',8,3,8,'STAGE MAQUETTAGE DE COMPOSANTS D''UN SIMULATEUR D''ENTRAINEMENT NAVAL','STAGE MAQUETTAGE DE COMPOSANTS D''UN SIMULATEUR D''ENTRAINEMENT NAVAL',to_timestamp('04/04/05 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('31/08/05 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),'Brest','EC','Atos Origin est l''un des principaux acteurs dans les domaines des services informatiques. Sa mission est de traduire la vision stratégique de ses clients en résultats par une meilleure utilisation de solutions de conseil, d''intégration et d''infogérance. Implanté dans 40 pays à travers le monde, Atos Origin réalise un chiffre d''affaires annuel de plus de 5 milliards d''euros avec un effectif supérieur à 46000 personnes. Atos Origin est le partenaire mondial des Jeux Olympiques. Au cSur du groupe Atos Origin, l''activité Systems Integration a pour vocation d''imaginer, de développer et de maintenir les systèmes d''information des entreprises. Le stage s''inscrit dans le cadre du projet PFE Sycops (Système de Combat Commun Barracuda et SNLE SG4) réalisé par Atos Origin pour le compte de la DCN de Brest (secteur défense). Ce projet recouvre l''étude, la réalisation et l''assistance à la mise en phase opérationnelle d''un simulateur d''entraînement et d''instruction pour le personnel navigant à bord des sous-marins nouvelle génération. Les entraînements propres aux élèves, s''effectuent de manière individuelle ou par équipe sur la base de scénarios conduits par un ou plusieurs instructeurs. Les principaux domaines didacticiels sont la détection sous-marine passive, la classification, le management de combat, le lancement des armes ainsi que le débriefing. Intégré au sein d''une équipe, vous serez chargé, à partir des résultats d''études de modélisation (Together sous Eclipse), de maquetter les applications ou les composants associés de type interface utilisateurs et techniques.Les outils qui seront mis en Suvre dans le cadre du stage reposent principalement sur l''atelier de développement Java et notamment Eclipse.L''outil de gestion de configuration sera CVS sous Eclipse.Le domaine fonctionnel concerne principalement la simulation temps réel.> Objectif pédagogique :A l''issue de cette mission, vous aurez développé une bonne approche sur le cycle de vie d''un projet réalisé au forfait et en équipe intégrée (Atos Origin et Thalès Services).La mission se déroulera à Brest. Le projet est réalisé en collaboration avec Thalès services Brest.','ELA',null,null,null,null,null,null,null,null);

Insert into STAGE (ANNEE_PRO,NO_ETUDIANT_NAT,NO_ENTREPRISE,NO_OFFRE,NO_CONTACT_ILI,INTITULE,SUJET,DATE_DEB,DATE_FIN,LIEU,ETAT_STAGE,DESCRIPTION,ETAT_CONVENTION,DATE_SIGNATURE_CONV,NO_ENSEIGNANT,COMMENTAIRE_TUTEUR,DATE_RECEPTION_RAPPORT,NOTE_ENTREPRISE,NOTE_RAPPORT,NO_SESSION,NOTE_SOUTENANCE) 
values ('2004-2005','20103546',0,null,0,'Non Défini','Non Défini',to_timestamp('10/10/12 16:14:53,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('10/10/12 16:14:53,000000000','DD/MM/RR HH24:MI:SS,FF'),'Non Défini','ELA',null,'ELA',null,null,null,null,null,null,null,null);

Insert into STAGE (ANNEE_PRO,NO_ETUDIANT_NAT,NO_ENTREPRISE,NO_OFFRE,NO_CONTACT_ILI,INTITULE,SUJET,DATE_DEB,DATE_FIN,LIEU,ETAT_STAGE,DESCRIPTION,ETAT_CONVENTION,DATE_SIGNATURE_CONV,NO_ENSEIGNANT,COMMENTAIRE_TUTEUR,DATE_RECEPTION_RAPPORT,NOTE_ENTREPRISE,NOTE_RAPPORT,NO_SESSION,NOTE_SOUTENANCE) 
values ('2004-2005','20168938',0,null,0,'Non Défini','Non Défini',to_timestamp('10/10/12 16:14:53,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('10/10/12 16:14:53,000000000','DD/MM/RR HH24:MI:SS,FF'),'Non Défini','ELA',null,'ELA',null,null,null,null,null,null,null,null);

Insert into STAGE (ANNEE_PRO,NO_ETUDIANT_NAT,NO_ENTREPRISE,NO_OFFRE,NO_CONTACT_ILI,INTITULE,SUJET,DATE_DEB,DATE_FIN,LIEU,ETAT_STAGE,DESCRIPTION,ETAT_CONVENTION,DATE_SIGNATURE_CONV,NO_ENSEIGNANT,COMMENTAIRE_TUTEUR,DATE_RECEPTION_RAPPORT,NOTE_ENTREPRISE,NOTE_RAPPORT,NO_SESSION,NOTE_SOUTENANCE) 
values ('2004-2005','142398A23C2',0,null,0,'Non Défini','Non Défini',to_timestamp('10/10/12 16:14:53,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('10/10/12 16:14:53,000000000','DD/MM/RR HH24:MI:SS,FF'),'Non Défini','ELA',null,'ELA',null,null,null,null,null,null,null,null);

Insert into STAGE (ANNEE_PRO,NO_ETUDIANT_NAT,NO_ENTREPRISE,NO_OFFRE,NO_CONTACT_ILI,INTITULE,SUJET,DATE_DEB,DATE_FIN,LIEU,ETAT_STAGE,DESCRIPTION,ETAT_CONVENTION,DATE_SIGNATURE_CONV,NO_ENSEIGNANT,COMMENTAIRE_TUTEUR,DATE_RECEPTION_RAPPORT,NOTE_ENTREPRISE,NOTE_RAPPORT,NO_SESSION,NOTE_SOUTENANCE) 
values ('2004-2005','361245',0,null,0,'Non Défini','Non Défini',to_timestamp('10/10/12 16:14:53,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('10/10/12 16:14:53,000000000','DD/MM/RR HH24:MI:SS,FF'),'Non Défini','ELA',null,'ELA',null,null,null,null,null,null,null,null);

Insert into STAGE (ANNEE_PRO,NO_ETUDIANT_NAT,NO_ENTREPRISE,NO_OFFRE,NO_CONTACT_ILI,INTITULE,SUJET,DATE_DEB,DATE_FIN,LIEU,ETAT_STAGE,DESCRIPTION,ETAT_CONVENTION,DATE_SIGNATURE_CONV,NO_ENSEIGNANT,COMMENTAIRE_TUTEUR,DATE_RECEPTION_RAPPORT,NOTE_ENTREPRISE,NOTE_RAPPORT,NO_SESSION,NOTE_SOUTENANCE) 
values ('2005-2006','1496024035g',3,2,1,'VoIP','Réalisation de briques réutilisables pour des services VoIP',to_timestamp('04/04/05 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('31/08/05 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),'Lannion','EC','Dans le cadre de son activité Lannionaise, Teamlog réalise pour ses clients des services basés sur des solutions voix sur IP destiné à des équipements types LiveBox. Ces services nécessitent la mise en Suvre de composants logiciels pour l''émission de vidéo, d''images, de texte et de son sur protocole RTP avec une signalisation SIP. Teamlog souhaite faire réaliser une bibliothèque de composants Java réutilisables par ces différents services. Réalisé en mode projet (spécifications, conception ...) au sein des équipes de Teamlog Lannion, le stage sera organisé avec phase de montée en compétence, prototypage et développement et avec le soutien des experts locaux. Technologies mises en Suvre : Java/J2EE, JMF (Java Media Framework), SIP-Servlet, Eclipse','ELA',null,1,null,null,null,null,1,null);

Insert into STAGE (ANNEE_PRO,NO_ETUDIANT_NAT,NO_ENTREPRISE,NO_OFFRE,NO_CONTACT_ILI,INTITULE,SUJET,DATE_DEB,DATE_FIN,LIEU,ETAT_STAGE,DESCRIPTION,ETAT_CONVENTION,DATE_SIGNATURE_CONV,NO_ENSEIGNANT,COMMENTAIRE_TUTEUR,DATE_RECEPTION_RAPPORT,NOTE_ENTREPRISE,NOTE_RAPPORT,NO_SESSION,NOTE_SOUTENANCE) 
values ('2005-2006','1499067588s',0,null,0,'Non defini','Non Defini',to_timestamp('03/10/06 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('03/10/05 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),'Non Defini','EC',null,'ELA',null,null,null,null,null,null,null,null);

Insert into STAGE (ANNEE_PRO,NO_ETUDIANT_NAT,NO_ENTREPRISE,NO_OFFRE,NO_CONTACT_ILI,INTITULE,SUJET,DATE_DEB,DATE_FIN,LIEU,ETAT_STAGE,DESCRIPTION,ETAT_CONVENTION,DATE_SIGNATURE_CONV,NO_ENSEIGNANT,COMMENTAIRE_TUTEUR,DATE_RECEPTION_RAPPORT,NOTE_ENTREPRISE,NOTE_RAPPORT,NO_SESSION,NOTE_SOUTENANCE) 
values ('2005-2006','1492092540t',0,null,0,'Non defini','Non Defini',to_timestamp('03/10/06 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('03/10/05 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),'Non Defini','EC',null,'ELA',null,null,null,null,null,null,null,null);

Insert into STAGE (ANNEE_PRO,NO_ETUDIANT_NAT,NO_ENTREPRISE,NO_OFFRE,NO_CONTACT_ILI,INTITULE,SUJET,
DATE_DEB,DATE_FIN,
LIEU,ETAT_STAGE,DESCRIPTION,ETAT_CONVENTION,DATE_SIGNATURE_CONV,NO_ENSEIGNANT,COMMENTAIRE_TUTEUR,DATE_RECEPTION_RAPPORT,NOTE_ENTREPRISE,NOTE_RAPPORT,NO_SESSION,NOTE_SOUTENANCE) 
values ('2005-2006','07is8800515',2,null,2,'Adaptation d''un processus de fabrication d''un progiciel au sein d''une PME','Adaptation d''un processus de fabrication d''un progiciel au sein d''une PME',
to_timestamp('04/04/05 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('31/08/05 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),
'Concarneau','EC',null,'ELA',null,1,null,null,11,null,1,null);

Insert into STAGE (ANNEE_PRO,NO_ETUDIANT_NAT,NO_ENTREPRISE,NO_OFFRE,NO_CONTACT_ILI,INTITULE,SUJET,DATE_DEB,DATE_FIN,LIEU,ETAT_STAGE,DESCRIPTION,ETAT_CONVENTION,DATE_SIGNATURE_CONV,NO_ENSEIGNANT,COMMENTAIRE_TUTEUR,DATE_RECEPTION_RAPPORT,NOTE_ENTREPRISE,NOTE_RAPPORT,NO_SESSION,NOTE_SOUTENANCE) 
values ('2005-2006','1493010305n',0,null,0,'Non defini','Non Defini',to_timestamp('03/10/06 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('03/10/05 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),'Non Defini','EC',null,'ELA',null,null,null,null,null,null,null,null);

Insert into STAGE (ANNEE_PRO,NO_ETUDIANT_NAT,NO_ENTREPRISE,NO_OFFRE,NO_CONTACT_ILI,INTITULE,SUJET,DATE_DEB,DATE_FIN,LIEU,ETAT_STAGE,DESCRIPTION,ETAT_CONVENTION,DATE_SIGNATURE_CONV,NO_ENSEIGNANT,COMMENTAIRE_TUTEUR,DATE_RECEPTION_RAPPORT,NOTE_ENTREPRISE,NOTE_RAPPORT,NO_SESSION,NOTE_SOUTENANCE) 
values ('2005-2006','1492057895k',0,null,0,'Non defini','Non Defini',to_timestamp('03/10/06 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('03/10/05 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),'Non Defini','EC',null,'ELA',null,null,null,null,null,null,null,null);

Insert into STAGE (ANNEE_PRO,NO_ETUDIANT_NAT,NO_ENTREPRISE,NO_OFFRE,NO_CONTACT_ILI,INTITULE,SUJET,DATE_DEB,DATE_FIN,LIEU,ETAT_STAGE,DESCRIPTION,ETAT_CONVENTION,DATE_SIGNATURE_CONV,NO_ENSEIGNANT,COMMENTAIRE_TUTEUR,DATE_RECEPTION_RAPPORT,NOTE_ENTREPRISE,NOTE_RAPPORT,NO_SESSION,NOTE_SOUTENANCE) 
values ('2005-2006','06816q06pf3',0,null,0,'Non defini','Non Defini',to_timestamp('03/10/06 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('03/10/05 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),'Non Defini','EC',null,'ELA',null,null,null,null,null,null,null,null);

Insert into STAGE (ANNEE_PRO,NO_ETUDIANT_NAT,NO_ENTREPRISE,NO_OFFRE,NO_CONTACT_ILI,INTITULE,SUJET,DATE_DEB,DATE_FIN,LIEU,ETAT_STAGE,DESCRIPTION,ETAT_CONVENTION,DATE_SIGNATURE_CONV,NO_ENSEIGNANT,COMMENTAIRE_TUTEUR,DATE_RECEPTION_RAPPORT,NOTE_ENTREPRISE,NOTE_RAPPORT,NO_SESSION,NOTE_SOUTENANCE) 
values ('2005-2006','1499110659h',0,null,0,'Non defini','Non Defini',to_timestamp('03/10/06 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('03/10/05 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),'Non Defini','EC',null,'ELA',null,null,null,null,null,null,null,null);

Insert into STAGE (ANNEE_PRO,NO_ETUDIANT_NAT,NO_ENTREPRISE,NO_OFFRE,NO_CONTACT_ILI,INTITULE,SUJET,DATE_DEB,DATE_FIN,LIEU,ETAT_STAGE,DESCRIPTION,ETAT_CONVENTION,DATE_SIGNATURE_CONV,NO_ENSEIGNANT,COMMENTAIRE_TUTEUR,DATE_RECEPTION_RAPPORT,NOTE_ENTREPRISE,NOTE_RAPPORT,NO_SESSION,NOTE_SOUTENANCE) 
values ('2005-2006','1893029650z',0,null,0,'Non defini','Non Defini',to_timestamp('03/10/06 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('03/10/05 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),'Non Defini','EC',null,'ELA',null,null,null,null,null,null,null,null);

Insert into STAGE (ANNEE_PRO,NO_ETUDIANT_NAT,NO_ENTREPRISE,NO_OFFRE,NO_CONTACT_ILI,INTITULE,SUJET,DATE_DEB,DATE_FIN,LIEU,ETAT_STAGE,DESCRIPTION,ETAT_CONVENTION,DATE_SIGNATURE_CONV,NO_ENSEIGNANT,COMMENTAIRE_TUTEUR,DATE_RECEPTION_RAPPORT,NOTE_ENTREPRISE,NOTE_RAPPORT,NO_SESSION,NOTE_SOUTENANCE) 
values ('2005-2006','1493003704n',0,null,0,'Non defini','Non Defini',to_timestamp('03/10/06 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('03/10/05 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),'Non Defini','EC',null,'ELA',null,null,null,null,null,null,null,null);
