-- INSERTING into VISITE_STAGE
Insert into "VISITE_STAGE" ("NO_ETUDIANT_NAT","ANNEE_PRO","NO_CONTACT_ILI","TYPE_CONTACT","DATE_PREVISIONNELLE","HEURE_PREVISIONNELLE","DATE_EFFECTIVE","HEURE_EFFECTIVE","DUREE","COMMENTAIRE_TUTEUR_UBO") 
values ('1496024035g','2005-2006',1,'ENT',to_date('2006-08-18','yyyy-mm-dd'),null,to_date('2006-08-30','yyyy-mm-dd'),null,'3 Heures','RAS');
Insert into "VISITE_STAGE" ("NO_ETUDIANT_NAT","ANNEE_PRO","NO_CONTACT_ILI","TYPE_CONTACT","DATE_PREVISIONNELLE","HEURE_PREVISIONNELLE","DATE_EFFECTIVE","HEURE_EFFECTIVE","DUREE","COMMENTAIRE_TUTEUR_UBO") 
values ('18986523','2004-2005',8,'ENT',to_date('2005-08-18','yyyy-mm-dd'),null,to_date('2005-08-30','yyyy-mm-dd'),null,'3 Heures','RAS');
Insert into "VISITE_STAGE" ("NO_ETUDIANT_NAT","ANNEE_PRO","NO_CONTACT_ILI","TYPE_CONTACT","DATE_PREVISIONNELLE","HEURE_PREVISIONNELLE","DATE_EFFECTIVE","HEURE_EFFECTIVE","DUREE","COMMENTAIRE_TUTEUR_UBO") 
values ('16894563','2004-2005',9,'ENT',to_date('2005-08-18','yyyy-mm-dd'),null,to_date('2005-08-30','yyyy-mm-dd'),null,'3 Heures','RAS');
