--
--  Création du jeu d'essai de la table AUTHENTIFICATION
--

Insert into AUTHENTIFICATION (ID_CONNECTION,ROLE,LOGIN_CONNECTION,PSEUDO_CONNECTION,MOT_PASSE,NO_ENSEIGNANT,NO_ETUDIANT) values (null,'ADM','Administrateur','adm','dosi',NULL,NULL);

Insert into AUTHENTIFICATION (ID_CONNECTION,ROLE,LOGIN_CONNECTION,PSEUDO_CONNECTION,MOT_PASSE,NO_ENSEIGNANT,NO_ETUDIANT) values (null,'SEC','xavier.denis@univ-brest.fr','xd','dosi',NULL,NULL);

Insert into AUTHENTIFICATION (ID_CONNECTION,ROLE,LOGIN_CONNECTION,PSEUDO_CONNECTION,MOT_PASSE,NO_ENSEIGNANT,NO_ETUDIANT) values (null,'SEC','nicolas.premel@univ-brest.fr','np','dosi',NULL,NULL);

Insert into AUTHENTIFICATION (ID_CONNECTION,ROLE,LOGIN_CONNECTION,PSEUDO_CONNECTION,MOT_PASSE,NO_ENSEIGNANT,NO_ETUDIANT) values (null,'ENS','philippe.saliou@univ-brest.fr','psaliou','dosi','1',NULL);

Insert into AUTHENTIFICATION (ID_CONNECTION,ROLE,LOGIN_CONNECTION,PSEUDO_CONNECTION,MOT_PASSE,NO_ENSEIGNANT,NO_ETUDIANT) values (null,'ENS','guillaume.bourel@univ-brest.fr','gb','dosi','3',NULL);

Insert into AUTHENTIFICATION (ID_CONNECTION,ROLE,LOGIN_CONNECTION,PSEUDO_CONNECTION,MOT_PASSE,NO_ENSEIGNANT,NO_ETUDIANT) values (null,'ENS','pierre.leroux@univ-brest.fr','plr','dosi','4',NULL);

Insert into AUTHENTIFICATION (ID_CONNECTION,ROLE,LOGIN_CONNECTION,PSEUDO_CONNECTION,MOT_PASSE,NO_ENSEIGNANT,NO_ETUDIANT) values (null,'ENS','mounir.lallali@univ-brest.fr','ml','dosi','2',NULL);

Insert into AUTHENTIFICATION (ID_CONNECTION,ROLE,LOGIN_CONNECTION,PSEUDO_CONNECTION,MOT_PASSE,NO_ENSEIGNANT,NO_ETUDIANT) values (null,'ETU','afkir.zakaria@univ-brest.fr','az','dosi',NULL,'21406961');

Insert into AUTHENTIFICATION (ID_CONNECTION,ROLE,LOGIN_CONNECTION,PSEUDO_CONNECTION,MOT_PASSE,NO_ENSEIGNANT,NO_ETUDIANT) values (null,'ETU','Ait.adnane@gmail.com','aa','dosi',NULL,'21406954');

Insert into AUTHENTIFICATION (ID_CONNECTION,ROLE,LOGIN_CONNECTION,PSEUDO_CONNECTION,MOT_PASSE,NO_ENSEIGNANT,NO_ETUDIANT) values (null,'ETU','hamza.aitmbarek@edu.uiz.ac.ma','ha','dosi',NULL,'21406912');
