--
--  Création du jeu d'essai de la table CANDIDAT
--

Insert into CANDIDAT (NO_CANDIDAT,CODE_FORMATION,ANNEE_UNIVERSITAIRE,NOM,PRENOM,SEXE,DATE_NAISSANCE,LIEU_NAISSANCE,NATIONALITE,TELEPHONE,MOBILE,EMAIL,ADRESSE,CODE_POSTAL,VILLE,PAYS_ORIGINE,UNIVERSITE_ORIGINE,LISTE_SELECTION,SELECTION_NO_ORDRE,CONFIRMATION_CANDIDAT,DATE_REPONSE_CANDIDAT) 
values ('10','M2DOSI','2014-2015','Afkir','Zakaria','H',to_date('09/02/92','DD/MM/RR'),'Tanger','Marocaine',null,'06 61 13 60 05','afkir.zakaria@gmail.com','4 avenue Hassan 1er','40000','MARRAKECH','MA','UAE','LP',null,'O',null);

Insert into CANDIDAT (NO_CANDIDAT,CODE_FORMATION,ANNEE_UNIVERSITAIRE,NOM,PRENOM,SEXE,DATE_NAISSANCE,LIEU_NAISSANCE,NATIONALITE,TELEPHONE,MOBILE,EMAIL,ADRESSE,CODE_POSTAL,VILLE,PAYS_ORIGINE,UNIVERSITE_ORIGINE,LISTE_SELECTION,SELECTION_NO_ORDRE,CONFIRMATION_CANDIDAT,DATE_REPONSE_CANDIDAT) 
values ('20','M2DOSI','2014-2015','Ait El Hafiane','Adnane','H',to_date('03/09/99','DD/MM/RR'),'Marrakech','Marocaine',null,'06 64 32 76 85','Ait.adnane@gmail.com','4 avenue Hassan 1er','40000','MARRAKECH','MA','UCAM','LP',null,'O',null);

Insert into CANDIDAT (NO_CANDIDAT,CODE_FORMATION,ANNEE_UNIVERSITAIRE,NOM,PRENOM,SEXE,DATE_NAISSANCE,LIEU_NAISSANCE,NATIONALITE,TELEPHONE,MOBILE,EMAIL,ADRESSE,CODE_POSTAL,VILLE,PAYS_ORIGINE,UNIVERSITE_ORIGINE,LISTE_SELECTION,SELECTION_NO_ORDRE,CONFIRMATION_CANDIDAT,DATE_REPONSE_CANDIDAT) 
values ('30','M2DOSI','2014-2015','Ait M''Barek','Hamza','H',to_date('02/11/91','DD/MM/RR'),'Agadir','Marocaine',null,'07 82 34 89 60','hamza.aitmbarek@edu.uiz.ac.ma','4 avenue Hassan 1er','40000','MARRAKECH','MA','UIZ','LP',null,'O',null);

Insert into CANDIDAT (NO_CANDIDAT,CODE_FORMATION,ANNEE_UNIVERSITAIRE,NOM,PRENOM,SEXE,DATE_NAISSANCE,LIEU_NAISSANCE,NATIONALITE,TELEPHONE,MOBILE,EMAIL,ADRESSE,CODE_POSTAL,VILLE,PAYS_ORIGINE,UNIVERSITE_ORIGINE,LISTE_SELECTION,SELECTION_NO_ORDRE,CONFIRMATION_CANDIDAT,DATE_REPONSE_CANDIDAT) 
values ('40','M2DOSI','2014-2015','Aterhzaz','Mohcine','H',to_date('29/05/91','DD/MM/RR'),'Marrakech','Marocaine',null,'06 64 94 22 68','aterhzaz.tr@gmail.com','4 avenue Hassan 1er','40000','MARRAKECH','MA','UCAM','LP',null,'O',null);

Insert into CANDIDAT (NO_CANDIDAT,CODE_FORMATION,ANNEE_UNIVERSITAIRE,NOM,PRENOM,SEXE,DATE_NAISSANCE,LIEU_NAISSANCE,NATIONALITE,TELEPHONE,MOBILE,EMAIL,ADRESSE,CODE_POSTAL,VILLE,PAYS_ORIGINE,UNIVERSITE_ORIGINE,LISTE_SELECTION,SELECTION_NO_ORDRE,CONFIRMATION_CANDIDAT,DATE_REPONSE_CANDIDAT) 
values ('50','M2DOSI','2014-2015','Barghane','Youssef','H',to_date('11/09/92','DD/MM/RR'),'Agadir','Marocaine',null,'07 82 73 87 30','youssef.barghane@gmail.com','4 avenue Hassan 1er','40000','MARRAKECH','MA','UIZ','LP',null,'O',null);

Insert into CANDIDAT (NO_CANDIDAT,CODE_FORMATION,ANNEE_UNIVERSITAIRE,NOM,PRENOM,SEXE,DATE_NAISSANCE,LIEU_NAISSANCE,NATIONALITE,TELEPHONE,MOBILE,EMAIL,ADRESSE,CODE_POSTAL,VILLE,PAYS_ORIGINE,UNIVERSITE_ORIGINE,LISTE_SELECTION,SELECTION_NO_ORDRE,CONFIRMATION_CANDIDAT,DATE_REPONSE_CANDIDAT) 
values ('60','M2DOSI','2014-2015','Baroudi','Soufiane','H',to_date('20/02/92','DD/MM/RR'),'Agadir','Marocaine',null,'06 61 13 60 05','soufiane.baroudi@gmail.com','4 avenue Hassan 1er','40000','MARRAKECH','MA','UIZ','LP',null,'O',null);

Insert into CANDIDAT (NO_CANDIDAT,CODE_FORMATION,ANNEE_UNIVERSITAIRE,NOM,PRENOM,SEXE,DATE_NAISSANCE,LIEU_NAISSANCE,NATIONALITE,TELEPHONE,MOBILE,EMAIL,ADRESSE,CODE_POSTAL,VILLE,PAYS_ORIGINE,UNIVERSITE_ORIGINE,LISTE_SELECTION,SELECTION_NO_ORDRE,CONFIRMATION_CANDIDAT,DATE_REPONSE_CANDIDAT) 
values ('70','M2DOSI','2014-2015','Bousraref','Badr','H',to_date('18/07/91','DD/MM/RR'),'Kénitra','Marocaine',null,'07 82 52 47 08','bousraref.badr@gmail.com','4 avenue Hassan 1er','40000','MARRAKECH','MA','UIT','LP',null,'O',null);

Insert into CANDIDAT (NO_CANDIDAT,CODE_FORMATION,ANNEE_UNIVERSITAIRE,NOM,PRENOM,SEXE,DATE_NAISSANCE,LIEU_NAISSANCE,NATIONALITE,TELEPHONE,MOBILE,EMAIL,ADRESSE,CODE_POSTAL,VILLE,PAYS_ORIGINE,UNIVERSITE_ORIGINE,LISTE_SELECTION,SELECTION_NO_ORDRE,CONFIRMATION_CANDIDAT,DATE_REPONSE_CANDIDAT) 
values ('80','M2DOSI','2014-2015','Chaabi','Laila','F',to_date('04/02/92','DD/MM/RR'),'Kénitra','Marocaine',null,'07 54 49 92 69','laila.chaabi@gmail.com','4 avenue Hassan 1er','40000','MARRAKECH','MA','UIT','LP',null,'O',null);

Insert into CANDIDAT (NO_CANDIDAT,CODE_FORMATION,ANNEE_UNIVERSITAIRE,NOM,PRENOM,SEXE,DATE_NAISSANCE,LIEU_NAISSANCE,NATIONALITE,TELEPHONE,MOBILE,EMAIL,ADRESSE,CODE_POSTAL,VILLE,PAYS_ORIGINE,UNIVERSITE_ORIGINE,LISTE_SELECTION,SELECTION_NO_ORDRE,CONFIRMATION_CANDIDAT,DATE_REPONSE_CANDIDAT) 
values ('90','M2DOSI','2014-2015','El Arbaoui','Salwa','F',to_date('01/08/92','DD/MM/RR'),'Tanger','Marocaine',null,'06 64 41 28 05','salwaelarbaoui@gmail.com','4 avenue Hassan 1er','40000','MARRAKECH','MA','UAE','LP',null,'O',null);

Insert into CANDIDAT (NO_CANDIDAT,CODE_FORMATION,ANNEE_UNIVERSITAIRE,NOM,PRENOM,SEXE,DATE_NAISSANCE,LIEU_NAISSANCE,NATIONALITE,TELEPHONE,MOBILE,EMAIL,ADRESSE,CODE_POSTAL,VILLE,PAYS_ORIGINE,UNIVERSITE_ORIGINE,LISTE_SELECTION,SELECTION_NO_ORDRE,CONFIRMATION_CANDIDAT,DATE_REPONSE_CANDIDAT) 
values ('100','M2DOSI','2014-2015','El Archaoui','Samira','F',to_date('23/12/90','DD/MM/RR'),'Kénitra','Marocaine',null,'06 64 85 76 53','elharchaouisamira@gmail.com','4 avenue Hassan 1er','40000','MARRAKECH','MA','UIT','LP',null,'O',null);

Insert into CANDIDAT (NO_CANDIDAT,CODE_FORMATION,ANNEE_UNIVERSITAIRE,NOM,PRENOM,SEXE,DATE_NAISSANCE,LIEU_NAISSANCE,NATIONALITE,TELEPHONE,MOBILE,EMAIL,ADRESSE,CODE_POSTAL,VILLE,PAYS_ORIGINE,UNIVERSITE_ORIGINE,LISTE_SELECTION,SELECTION_NO_ORDRE,CONFIRMATION_CANDIDAT,DATE_REPONSE_CANDIDAT) 
values ('110','M2DOSI','2013-2014','Biane','Mohamed','H',to_date('21/10/90','DD/MM/RR'),'Marrakech','Marocaine',null,'06 12 03 66 53','biane.mohamed@gmail.com','45 avenue Hassan II','40000','MARRAKECH','MA','UCAM','LP',null,'O',null);

Insert into CANDIDAT (NO_CANDIDAT,CODE_FORMATION,ANNEE_UNIVERSITAIRE,NOM,PRENOM,SEXE,DATE_NAISSANCE,LIEU_NAISSANCE,NATIONALITE,TELEPHONE,MOBILE,EMAIL,ADRESSE,CODE_POSTAL,VILLE,PAYS_ORIGINE,UNIVERSITE_ORIGINE,LISTE_SELECTION,SELECTION_NO_ORDRE,CONFIRMATION_CANDIDAT,DATE_REPONSE_CANDIDAT) 
values ('120','M2DOSI','2013-2014','El Khal','Sara','F',to_date('09/06/91','DD/MM/RR'),'Marrakech','Marocaine',null,'06 34 94 55 28','elkhal.sara@gmail.com','66 avenue Hassan 1er','40000','MARRAKECH','MA','UCAM','LP',null,'O',null);
