--
--  Création du jeu d'essai de la table ELEMENT_CONSTITUTIF
--

Insert into ELEMENT_CONSTITUTIF (CODE_FORMATION,CODE_UE,CODE_EC,NO_ENSEIGNANT,DESIGNATION,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) 
values ('M2DOSI','PCO','ERP','6','Intégration de progiciels',null,'6','6','6');

Insert into ELEMENT_CONSTITUTIF (CODE_FORMATION,CODE_UE,CODE_EC,NO_ENSEIGNANT,DESIGNATION,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) 
values ('M2DOSI','PCO','SFM','1','Stage en France pré-embauche Maroc','Préparation au stage en France dans une perspective d''embauche au Maroc','6','6','6');

Insert into ELEMENT_CONSTITUTIF (CODE_FORMATION,CODE_UE,CODE_EC,NO_ENSEIGNANT,DESIGNATION,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) 
values ('M2DOSI','J2EE','CME','2','Couche Métier','EJB,REST et JPA','12','12','12');

Insert into ELEMENT_CONSTITUTIF (CODE_FORMATION,CODE_UE,CODE_EC,NO_ENSEIGNANT,DESIGNATION,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) 
values ('M2DOSI','J2EE','CPR','4','Couche Présentation','SPRING MVC','4','4','4');
