--
--  Création du jeu d'essai de la table ETUDIANT
--

Insert into ETUDIANT (NO_ETUDIANT,CODE_FORMATION,ANNEE_UNIVERSITAIRE,NOM,PRENOM,SEXE,DATE_NAISSANCE,LIEU_NAISSANCE,NATIONALITE,TELEPHONE,MOBILE,EMAIL,EMAIL_UBO,ADRESSE,CODE_POSTAL,VILLE,PAYS_ORIGINE,UNIVERSITE_ORIGINE,GROUPE_TP,GROUPE_ANGLAIS) 
values ('21406961','M2DOSI','2014-2015','AFKIR','Zakaria','M',to_date('09/02/92','DD/MM/RR'),'Tanger','Marocaine',null,'06 61 13 60 05','afkir.zakaria@gmail.com','afkir.zakaria@univ-brest.fr','2 rue des Archives','29287','BREST','MA','UAE','1','1');

Insert into ETUDIANT (NO_ETUDIANT,CODE_FORMATION,ANNEE_UNIVERSITAIRE,NOM,PRENOM,SEXE,DATE_NAISSANCE,LIEU_NAISSANCE,NATIONALITE,TELEPHONE,MOBILE,EMAIL,EMAIL_UBO,ADRESSE,CODE_POSTAL,VILLE,PAYS_ORIGINE,UNIVERSITE_ORIGINE,GROUPE_TP,GROUPE_ANGLAIS) 
values ('21406954','M2DOSI','2014-2015','AIT EL HAFIANE','Adnane','M',to_date('03/09/99','DD/MM/RR'),'Marrakech','Marocaine',null,'06 64 32 76 85','Ait.adnane@gmail.com','Ait.adnane@univ-brest.fr','2 rue des Archives','29287','BREST','MA','UCAM','1','1');

Insert into ETUDIANT (NO_ETUDIANT,CODE_FORMATION,ANNEE_UNIVERSITAIRE,NOM,PRENOM,SEXE,DATE_NAISSANCE,LIEU_NAISSANCE,NATIONALITE,TELEPHONE,MOBILE,EMAIL,EMAIL_UBO,ADRESSE,CODE_POSTAL,VILLE,PAYS_ORIGINE,UNIVERSITE_ORIGINE,GROUPE_TP,GROUPE_ANGLAIS) 
values ('21406912','M2DOSI','2014-2015','AIT M''BAREK','Hamza','M',to_date('02/11/91','DD/MM/RR'),'Agadir','Marocaine',null,'07 82 34 89 60','hamza.aitmbarek@edu.uiz.ac.ma','hamza.aitmbarek@univ-brest.fr','2 rue des Archives','29287','BREST','MA','UIZ','1','1');

Insert into ETUDIANT (NO_ETUDIANT,CODE_FORMATION,ANNEE_UNIVERSITAIRE,NOM,PRENOM,SEXE,DATE_NAISSANCE,LIEU_NAISSANCE,NATIONALITE,TELEPHONE,MOBILE,EMAIL,EMAIL_UBO,ADRESSE,CODE_POSTAL,VILLE,PAYS_ORIGINE,UNIVERSITE_ORIGINE,GROUPE_TP,GROUPE_ANGLAIS) 
values ('21406882','M2DOSI','2014-2015','ATERHZAZ','Mohcine','M',to_date('29/05/91','DD/MM/RR'),'Marrakech','Marocaine',null,'06 64 94 22 68','aterhzaz.tr@gmail.com','aterhzaz.tr@univ-brest.fr','2 rue des Archives','29287','BREST','MA','UCAM','1','1');

Insert into ETUDIANT (NO_ETUDIANT,CODE_FORMATION,ANNEE_UNIVERSITAIRE,NOM,PRENOM,SEXE,DATE_NAISSANCE,LIEU_NAISSANCE,NATIONALITE,TELEPHONE,MOBILE,EMAIL,EMAIL_UBO,ADRESSE,CODE_POSTAL,VILLE,PAYS_ORIGINE,UNIVERSITE_ORIGINE,GROUPE_TP,GROUPE_ANGLAIS) 
values ('21406940','M2DOSI','2014-2015','BARGHANE','Youssef','M',to_date('11/09/92','DD/MM/RR'),'Agadir','Marocaine',null,'07 82 73 87 30','youssef.barghane@gmail.com','youssef.barghane@univ-brest.fr','2 rue des Archives','29287','BREST','MA','UIZ','1','1');

Insert into ETUDIANT (NO_ETUDIANT,CODE_FORMATION,ANNEE_UNIVERSITAIRE,NOM,PRENOM,SEXE,DATE_NAISSANCE,LIEU_NAISSANCE,NATIONALITE,TELEPHONE,MOBILE,EMAIL,EMAIL_UBO,ADRESSE,CODE_POSTAL,VILLE,PAYS_ORIGINE,UNIVERSITE_ORIGINE,GROUPE_TP,GROUPE_ANGLAIS) 
values ('21406919','M2DOSI','2014-2015','BAROUDI','Soufiane','M',to_date('20/02/92','DD/MM/RR'),'Agadir','Marocaine',null,'06 61 13 60 05','soufiane.baroudi@gmail.com','soufiane.baroudi@univ-brest.fr','2 rue des Archives','29287','BREST','MA','UIZ','2','1');

Insert into ETUDIANT (NO_ETUDIANT,CODE_FORMATION,ANNEE_UNIVERSITAIRE,NOM,PRENOM,SEXE,DATE_NAISSANCE,LIEU_NAISSANCE,NATIONALITE,TELEPHONE,MOBILE,EMAIL,EMAIL_UBO,ADRESSE,CODE_POSTAL,VILLE,PAYS_ORIGINE,UNIVERSITE_ORIGINE,GROUPE_TP,GROUPE_ANGLAIS) 
values ('21406958','M2DOSI','2014-2015','BOUSRAREF','Badr','M',to_date('18/07/91','DD/MM/RR'),'Kénitra','Marocaine',null,'07 82 52 47 08','bousraref.badr@gmail.com','bousraref.badr@univ-brest.fr','2 rue des Archives','29287','BREST','MA','UIT','1','1');

Insert into ETUDIANT (NO_ETUDIANT,CODE_FORMATION,ANNEE_UNIVERSITAIRE,NOM,PRENOM,SEXE,DATE_NAISSANCE,LIEU_NAISSANCE,NATIONALITE,TELEPHONE,MOBILE,EMAIL,EMAIL_UBO,ADRESSE,CODE_POSTAL,VILLE,PAYS_ORIGINE,UNIVERSITE_ORIGINE,GROUPE_TP,GROUPE_ANGLAIS) 
values ('21406948','M2DOSI','2014-2015','CHAABI','Laila','F',to_date('04/02/92','DD/MM/RR'),'Kénitra','Marocaine',null,'07 54 49 92 69','laila.chaabi@gmail.com','laila.chaabi@univ-brest.fr','2 rue des Archives','29287','BREST','MA','UIT','1','1');

Insert into ETUDIANT (NO_ETUDIANT,CODE_FORMATION,ANNEE_UNIVERSITAIRE,NOM,PRENOM,SEXE,DATE_NAISSANCE,LIEU_NAISSANCE,NATIONALITE,TELEPHONE,MOBILE,EMAIL,EMAIL_UBO,ADRESSE,CODE_POSTAL,VILLE,PAYS_ORIGINE,UNIVERSITE_ORIGINE,GROUPE_TP,GROUPE_ANGLAIS) 
values ('21406956','M2DOSI','2014-2015','EL ARBAOUI','Salwa','F',to_date('01/08/92','DD/MM/RR'),'Tanger','Marocaine',null,'06 64 41 28 05','salwaelarbaoui@gmail.com','salwaelarbaoui@univ-brest.fr','2 rue des Archives','29287','BREST','MA','UAE','1','1');

Insert into ETUDIANT (NO_ETUDIANT,CODE_FORMATION,ANNEE_UNIVERSITAIRE,NOM,PRENOM,SEXE,DATE_NAISSANCE,LIEU_NAISSANCE,NATIONALITE,TELEPHONE,MOBILE,EMAIL,EMAIL_UBO,ADRESSE,CODE_POSTAL,VILLE,PAYS_ORIGINE,UNIVERSITE_ORIGINE,GROUPE_TP,GROUPE_ANGLAIS) 
values ('21406946','M2DOSI','2014-2015','EL ARCHAOUI','Samira','M',to_date('23/12/90','DD/MM/RR'),'Kénitra','Marocaine',null,'06 64 85 76 53','elharchaouisamira@gmail.com','elharchaouisamira@univ-brest.fr','2 rue des Archives','29287','BREST','MA','UIT','1','1');

