--
--  Création du jeu d'essai de la table PROMOTION
--

Insert into PROMOTION (CODE_FORMATION,ANNEE_UNIVERSITAIRE,NO_ENSEIGNANT,SIGLE_PROMOTION,NB_MAX_ETUDIANT,DATE_REPONSE_LP,DATE_REPONSE_LALP,DATE_RENTREE,LIEU_RENTREE,PROCESSUS_STAGE,COMMENTAIRE) 
values ('M2DOSI','2013-2014','1','DOSI4','24',to_date('04/05/13','DD/MM/RR'),to_date('19/05/13','DD/MM/RR'),to_date('07/09/13','DD/MM/RR'),'LC117B','EC',null);

Insert into PROMOTION (CODE_FORMATION,ANNEE_UNIVERSITAIRE,NO_ENSEIGNANT,SIGLE_PROMOTION,NB_MAX_ETUDIANT,DATE_REPONSE_LP,DATE_REPONSE_LALP,DATE_RENTREE,LIEU_RENTREE,PROCESSUS_STAGE,COMMENTAIRE) 
values ('M2DOSI','2014-2015','1','DOSI5','24',to_date('10/05/14','DD/MM/RR'),to_date('19/05/14','DD/MM/RR'),to_date('08/09/14','DD/MM/RR'),'LC117B','RECH',null);

Insert into PROMOTION (CODE_FORMATION,ANNEE_UNIVERSITAIRE,NO_ENSEIGNANT,SIGLE_PROMOTION,NB_MAX_ETUDIANT,DATE_REPONSE_LP,DATE_REPONSE_LALP,DATE_RENTREE,LIEU_RENTREE,PROCESSUS_STAGE,COMMENTAIRE) 
values ('M1TIIL','2014-2015','6',NULL,'60',to_date('10/07/14','DD/MM/RR'),to_date('10/08/14','DD/MM/RR'),to_date('01/09/14','DD/MM/RR'),'LC117A','EC',null);
