--
--  Création du jeu d'essai de la table UNITE_ENSEIGNEMENT
--

Insert into UNITE_ENSEIGNEMENT (CODE_FORMATION,CODE_UE,NO_ENSEIGNANT,DESIGNATION,SEMESTRE,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) 
values ('M2DOSI','ISI','1','Ingénierie des Systèmes d''Information','9  ',null,'20','20','20');

Insert into UNITE_ENSEIGNEMENT (CODE_FORMATION,CODE_UE,NO_ENSEIGNANT,DESIGNATION,SEMESTRE,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) 
values ('M2DOSI','IDL','1','Ingénierie de Développement Logiciel','9  ',null,'20','20','20');

Insert into UNITE_ENSEIGNEMENT (CODE_FORMATION,CODE_UE,NO_ENSEIGNANT,DESIGNATION,SEMESTRE,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) 
values ('M2DOSI','J2EE','2','Java/J2EE','9  ',null,'20','20','20');

Insert into UNITE_ENSEIGNEMENT (CODE_FORMATION,CODE_UE,NO_ENSEIGNANT,DESIGNATION,SEMESTRE,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) 
values ('M2DOSI','SR','2','Systèmes Répartis','10 ',null,'20','20','20');

Insert into UNITE_ENSEIGNEMENT (CODE_FORMATION,CODE_UE,NO_ENSEIGNANT,DESIGNATION,SEMESTRE,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) 
values ('M2DOSI','EDE','3','Environnement de Développement','9  ',null,'0','0','48');

Insert into UNITE_ENSEIGNEMENT (CODE_FORMATION,CODE_UE,NO_ENSEIGNANT,DESIGNATION,SEMESTRE,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) 
values ('M2DOSI','WEB','3','Langages du WEB','9  ',null,'20','20','20');

Insert into UNITE_ENSEIGNEMENT (CODE_FORMATION,CODE_UE,NO_ENSEIGNANT,DESIGNATION,SEMESTRE,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) 
values ('M2DOSI','CO','5','Conception Objet','9  ',null,'20','20','20');

Insert into UNITE_ENSEIGNEMENT (CODE_FORMATION,CODE_UE,NO_ENSEIGNANT,DESIGNATION,SEMESTRE,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) 
values ('M2DOSI','PCO','1','Préparation au Contexte de l''Offshore','10 ',null,'16','16','16');
